/*1*/

SELECT SISTEMAPUNTOS
FROM TEMPORADA
WHERE PERIODO<'2017-18';

/*2*/

DELETE FROM EQUIPO
WHERE NOMBRE='Aguri';

/*No se puede eliminar al equipo Aguri debido a que el campo NOMBRE es una clave primaria que tiene una clave foránea dependiente.
Por lo tanto al eliminarla, su dependencia perdería el sentido que tiene*/

/*3*/

INSERT INTO PILOTO (CODPILOTO, NOMBRE, CODPAIS,FECHANACIMIENTO,LUGARNACIMIENTO, SEXO) VALUES ('MIGAZC', 'Miguel Azcárate', 'ES','08/07/99','Pamplona','H');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2016-17', 'MIGAZC', 'Renault', 'PR');

/*4*/

SELECT PERIODO,NUMEROCARRERAS
FROM TEMPORADA;

SELECT COUNT(FECHACARRERA)ncarreras
FROM CARRERA;

/*No es consistente, ya que en un resultado se muestra que han habido 4 carreras y en otro 5. */
/*Lo que se debería hacer es revisar la base de datos en el campo TEMPORADA y añadir la carrera que falta*/

/*5*/

SELECT P.NOMBRE_ESP, COUNT(C.NOMBRE)TOTAL_CIRCUITOS
FROM PAIS P, CIRCUITO C
WHERE P.CODPAIS=C.CODPAIS
GROUP BY P.NOMBRE_ESP;

/*6*/

SELECT C.NOMBRE, C.CURVAS,C.CIUDAD, P.NOMBRE_ESP
FROM PAIS P, CIRCUITO C
WHERE P.CODPAIS=C.CODPAIS
ORDER BY C.NOMBRE;

/*7*/

SELECT MIN(CURVAS)Menos_curvas
FROM CIRCUITO;

/*8*/

SELECT PI.CODPILOTO, MIN(PA.POSICION_LLEGADA) POSLLEGADA
FROM PILOTO PI, PARTICIPA PA
WHERE PA.CODPILOTO=PI.CODPILOTO
GROUP BY PI.CODPILOTO
ORDER BY POSLLEGADA;

/*9*/

SELECT C.FECHACARRERA, C.NOMBRE_GP
FROM CARRERA C, PILOTO PI, PARTICIPA PA
WHERE C.VUELTAS>35 AND PA.CODPILOTO=PI.CODPILOTO AND PA.FECHACARRERA=C.FECHACARRERA AND PI.NOMBRE='Katherine Legge';

/*10*/

SELECT E.NOMBRE, PER.PERIODO, PAIS.NOMBRE_ENG, COUNT (PER.CODPILOTO)
FROM EQUIPO E, PERTENECE PER, PAIS
WHERE E.NOMBRE=PER.EQUIPO AND E.CODPAIS=PAIS.CODPAIS AND PER.ROL!='PR'
GROUP BY E.NOMBRE, PER.PERIODO, PAIS.NOMBRE_ENG
HAVING COUNT (PER.CODPILOTO)>1;

/*11*/

SELECT PI.NOMBRE, COUNT(PA.FECHACARRERA)
FROM PILOTO PI, PARTICIPA PA
WHERE PA.CODPILOTO=PI.CODPILOTO AND PA.POSICION_LLEGADA IN (1,2,3)
GROUP BY PI.NOMBRE
HAVING COUNT(PA.FECHACARRERA)>3;

/*12*/

SELECT 'Las carreras en la diudad de '||C.CIUDAD||' suelen tener una media de '||AVG(C.LONGITUD)/10||' metros de recta entre curvas'
FROM CIRCUITO C
GROUP BY C.CIUDAD;

/*13*/

SELECT MIN(C.CURVAS),MAX(C.CURVAS)
FROM CIRCUITO C;

/*14*/

SELECT PI.NOMBRE, PAIS.NOMBRE_ESP Pais_piloto, CIR.NOMBRE,PAIS.NOMBRE_ENG Pais_circuito
FROM PILOTO PI, PAIS, CIRCUITO CIR
WHERE PI.CODPAIS=PAIS.CODPAIS AND CIR.CODPAIS=PAIS.CODPAIS
GROUP BY  PI.NOMBRE, PAIS.NOMBRE_ESP, CIR.NOMBRE,PAIS.NOMBRE_ENG
ORDER BY PI.NOMBRE;

/*15*/

SELECT CA.FECHACARRERA, CA.NOMBRE_GP, PI.NOMBRE, PI.CODPILOTO, (PA.POSICION_LLEGADA<PA.POSICION_SALIDA)
FROM CARRERA CA, PARTICIPA PA, PILOTO PI
WHERE CA.FECHACARRERA=PA.FECHACARRERA AND PI.CODPILOTO=PA.CODPILOTO AND (PA.POSICION_LLEGADA<PA.POSICION_SALIDA)
GROUP BY CA.FECHACARRERA, CA.NOMBRE_GP, PI.NOMBRE,PI.CODPILOTO;