CREATE TABLE USUARIO(
    NOMBRE VARCHAR(15),
    APELLIDO VARCHAR(15) NOT NULL,
    SEXO VARCHAR(1),
    EDAD NUMBER(3),
    COD_USER NUMBER(6),
    CONSTRAINT PK_USER PRIMARY KEY(COD_USER),
    CONSTRAINT REST_SEXO CHECK (SEXO IN ('M', 'F')),
    CONSTRAINT EDAD_MIN CHECK (EDAD > 15)
);

CREATE TABLE LIBROS(
    TITULO VARCHAR(25) NOT NULL,
    AUTOR VARCHAR(15),
    EDITORIAL VARCHAR(15),
    ISBN VARCHAR(20) NOT NULL,
    TIPO VARCHAR(1),
    CONSTRAINT PK_ISBN PRIMARY KEY (ISBN),
    CONSTRAINT UNICOS UNIQUE (TITULO),
    CONSTRAINT REST_CLASE CHECK (TIPO IN ('A', 'B', 'C', 'D', 'E')),
    CONSTRAINT RELATION_CLASE FOREIGN KEY (TIPO) REFERENCES CLASES (TIPO),
    ON DELETE CASCADE
);

CREATE TABLE CLASES(
    TIPO VARCHAR(1),
    TIEMPO NUMBER(1),
    CONSTRAINT PK_CLASES PRIMARY KEY (TIPO)
);    
    

CREATE TABLE PRESTAMOS(
    COD_PRESTAMO NUMBER(6),
    IN_FECHA DATE,
    OUT_FECHA DATE,
    COD_LIBRO VARCHAR(20),
    COD_USER NUMBER(6),
    CONSTRAINT PK_ISBN PRIMARY KEY (COD_PRESTAMO),
    CONSTRAINT REST_FECHA CHECK (OUT_FECHA > IN_FECHA),
    CONSTRAINT RELATION_LIBROS FOREIGN KEY (COD_LIBRO) REFERENCES LIBROS (ISBN),
    CONSTRAINT RELATION_USERS FOREIGN KEY (COD_USER) REFERENCES USUARIOS (COD_USER),
    ON DELETE CASCADE
);
    
/* PRESTAMOS DATA */
INSERT INTO CLASE VALUES ('A', 7);
INSERT INTO CLASE VALUES ('B', 30);
INSERT INTO CLASE VALUES ('C', 90);
INSERT INTO CLASE VALUES ('D', 180);
INSERT INTO CLASE VALUES ('E', 365);

/* Ejercicio 1 */
INSERT INTO USUARIOS VALUES ('Antonio', 'Gomez', 'M', 20, 1);

/* Ejercicio 2 */
INSERT INTO USUARIOS VALUES ('Jon', 'Alkorta', 'M', 10, 2);

/* Ejercicio 3*/
INSERT INTO LIBROS (TITULO, EDITORIAL, ISBN, ) VALUES ('Fichero', 'Anaya', '1FBD' );
INSERT INTO LIBROS VALUES ('Bases de Datos', );
INSERT INTO LIBROS VALUES ('', );


