CREATE TABLE USUARIO(
    NOMBRE VARCHAR(15),
    APELLIDO VARCHAR(15) NOT NULL,
    SEXO VARCHAR(1),
    EDAD NUMBER(3),
    NUM_USUARIO VARCHAR(6),
    CONSTRAINT COD_USUARIO PRIMARY KEY(NUM_USUARIO)
    CONSTRAINT REST_SEXO CHECK(SEXO IN ('M', 'F'))