/*Ejercicio 1*/
SELECT L.EDITORIAL, COUNT(L.TITULO) AS VOLUMENES
FROM LIBRO L
GROUP BY L.EDITORIAL
ORDER BY VOLUMENES DESC
;

/*Ejercicio 2*/
SELECT L.EDITORIAL, COUNT(P.ISBN) AS N튡RESTAMOS
FROM PRESTAMO P, LIBRO L
WHERE L.ISBN=P.ISBN 
GROUP BY L.EDITORIAL
ORDER BY N튡RESTAMOS DESC
;

/*Ejercicio 3*/
SELECT COUNT(P.ISBN)
FROM PRESTAMO P
;

/*Ejercicio 4*/
SELECT U.COD, U.NOMBRE, U.EDAD, COUNT(P.ISBN) AS N튡RESTAMO 
FROM USUARIO U,PRESTAMO P
WHERE U.COD=P.COD AND EDAD BETWEEN 20 AND 30
GROUP BY U.COD, U.NOMBRE, U.EDAD
HAVING COUNT(P.ISBN)>1
;

/*Ejercicio 5*/
SELECT U.COD, U.NOMBRE,U.APELLIDO, L.EDITORIAL, COUNT(P.ISBN) AS N튡RESTAMO
FROM USUARIO U, PRESTAMO P, LIBRO L
WHERE U.COD=P.COD AND P.ISBN=L.ISBN 
GROUP BY U.COD, U.NOMBRE,U.APELLIDO, L.EDITORIAL
HAVING COUNT(P.ISBN)>2
;

/*Ejercicio 6*/
SELECT L.ISBN, L.TITULO, L.AUTOR, P.FECHA_INI, P.FECHA_FIN
FROM LIBRO L, PRESTAMO P
WHERE P.FECHA_FIN IS null AND L.ISBN=P.ISBN
;
--Para ver si es null, no usar LIKE

/*Ejercicio 7A*/
SELECT L.ISBN
FROM LIBRO L, PRESTAMO P
WHERE P.FECHA_FIN IS null AND L.ISBN=P.ISBN
GROUP BY L.ISBN
HAVING COUNT(P.ISBN)>1
;
/*Ejercicio 7B*/
SELECT MAX(P.FECHA_INI)
FROM LIBRO L, PRESTAMO P
WHERE P.FECHA_FIN IS null AND L.ISBN=P.ISBN
GROUP BY L.ISBN
HAVING COUNT(P.ISBN)>1
;
--Uso este resultado y el anterior(6c)
SELECT L.ISBN, P.COD, P.FECHA_INI,P.FECHA_FIN
FROM PRESTAMO P, LIBRO L
WHERE L.ISBN=P.ISBN AND L.ISBN LIKE '6C' AND P.FECHA_INI NOT LIKE '04/07/19' AND P.FECHA_FIN IS null
;
DELETE FROM PRESTAMO P WHERE P.ISBN LIKE '6C' AND P.FECHA_INI NOT LIKE '04/07/19' AND P.FECHA_FIN IS null;

/*Ejercicio 8*/
SELECT U.COD, U.NOMBRE, U.APELLIDO, L.TITULO, C.TIEMPO, (P.FECHA_FIN - P.FECHA_INI) AS DIAS_PRESTAMO, ((P.FECHA_FIN - P.FECHA_INI)-C.TIEMPO) AS EXCEDIDOS
FROM PRESTAMO P, USUARIO U, LIBRO L, CLASELIBRO C  
WHERE U.COD=P.COD AND P.ISBN=L.ISBN AND L.CLASE=C.CLASE AND P.FECHA_FIN NOT LIKE 'null'
ORDER BY EXCEDIDOS DESC
;

/*Ejercicio 9*/
SELECT U.COD, U.NOMBRE, U.APELLIDO, L.TITULO, C.TIEMPO, P.FECHA_INI, SYSDATE , ROUND( (SYSDATE - P.FECHA_INI),3) AS DIAS_PRESTAMO, ROUND (((SYSDATE - P.FECHA_INI)-C.TIEMPO),3) AS EXCEDIDOS
FROM PRESTAMO P, USUARIO U, LIBRO L, CLASELIBRO C  
WHERE U.COD=P.COD AND P.ISBN=L.ISBN AND L.CLASE=C.CLASE AND P.FECHA_FIN IS null
ORDER BY U.APELLIDO ASC
;
--Sale 7 filas y no 8 por el borrado anterior

/*Ejercicio 10*/
SELECT COUNT(AUTOR)
FROM LIBRO
--WHERE LENGTH(AUTOR)=5-- no hemos visto funciones
WHERE AUTOR LIKE '_____'--5barras baja para indicar que solo quiero los nombres con 5 caractereres
;

/*Ejercicio 11*/
SELECT L.EDITORIAL, SUM(C.TIEMPO)
FROM LIBRO L, CLASELIBRO C
WHERE L.CLASE=C.CLASE
GROUP BY L.EDITORIAL
ORDER BY SUM(C.TIEMPO) ASC
;








