/* Practica 1 */

/*Ejercicio 1*/
SELECT CODIGO, NOMBRE
FROM DEPARTAMENTOS

/* Ejercicio 2 */
SELECT A.DEPARTAMENTO, A.CODIGO, A.NOMBRE
FROM AREAS A

/* Ejercicio 3 */
SELECT *
FROM LOCALES L
WHERE (L.CAPACIDAD > 30)

/* Ejercicio 4 */
SELECT *
FROM LOCALES L
WHERE ((L.CAPACIDAD > 30) AND (L.EDIFICIO = 'EGB'))

/* Ejercicio 5 */
SELECT *
FROM DOCENCIA D
ORDER BY D.PROFESOR, D.SIGLAS
/* duda: orden */

/* Ejercicio 6 */
SELECT D.ID, D.PROFESOR, D.SIGLAS, D.PERIODICIDAD
FROM DOCENCIA D
ORDER BY D.ID

/* Ejercicio 6 BIS*/
SELECT D.ID,D.PROFESOR,D.SIGLAS,A.ANUALIDAD,A.CREDITOS
FROM ASIGNATURAS A,DOCENCIA D
WHERE D.SIGLAS=A.SIGLAS;

/* Ejericicio 7 */
SELECT *
FROM ASIGNATURAS A
WHERE (A.HORAS_TEORIA > 0) AND (A.HORAS_PRACTICA > 0)

/* Ejericicio 7 BIS */
SELECT *
FROM ASIGNATURAS 
WHERE (HORAS_TEORIA > 0) AND (HORAS_PRACTICA > 0)


/* Ejericicio 8 */
SELECT *
FROM ASIGNATURAS A
WHERE (A.HORAS_TEORIA > 0) OR (A.HORAS_PRACTICA > 0)

/* Ejericicio 9 */
SELECT *
FROM ASIGNATURAS A
WHERE ((A.HORAS_TEORIA > 0) OR (A.HORAS_PRACTICA > 0)) AND (A.ALUMNOS > 30)

/* Ejericicio 10 */
SELECT DISTINCT D.GRUPO
FROM DOCENCIA D
ORDER BY D.GRUPO ASC

/* Ejericicio 11 */
SELECT A.SIGLAS, A.ALUMNOS
FROM ASIGNATURAS A
WHERE A.ANUALIDAD = 'A'

/* Ejercicio 12 */
SELECT L.EDIFICIO 
FROM LOCALES L
WHERE (L.EDIFICIO LIKE 'E%')

/* Ejercicio 13 */
SELECT *
FROM LOCALES L
WHERE (L.CAPACIDAD BETWEEN 30 AND 80)

/* Ejercicio 14 */
SELECT *
FROM LOCALES L
WHERE (L.SITUACION NOT LIKE 'Planta Primera%' )

/* Ejercicio 15 */
SELECT SIGLAS, NOMBRE, CREDITOS, CURSO, ANUALIDAD, CLASE, HORAS_TEORIA, HORAS_PRACTICA *1.1 "Previsión Profesorado"
FROM ASIGNATURAS 
WHERE (HORAS_PRACTICA > 0)

/* Ejercicio 16 */
SELECT 'El area de codigo '||A.CODIGO||' pertence al departamento '||A.DEPARTAMENTO
FROM AREAS A

/* Ejercicio 17 */
SELECT DISTINCT P.CODIGO||'-'||P.APELLIDO1||'    '||P.APELLIDO2||'   , '|| P.NOMBRE_PILA 
FROM PROFESORES P
WHERE P.ACTIVO = 1

/* Extra */
SELECT *
FROM ASIGNATURAS
WHERE ANUALIDAD IS NULL

/* Ejercicio 18 */
SELECT DISTINCT D.CODIGO, D.NOMBRE, A.CODIGO, A.NOMBRE
FROM DEPARTAMENTOS D, AREAS A
WHERE A.DEPARTAMENTO = D.CODIGO
ORDER BY D.CODIGO, A.CODIGO;

/* Ejercicio 19 */
SELECT D.ID,D.CURSO,D.CLASE,D.GRUPO,D.SIGLAS,D.PROFESOR,D.LOCAL,D.DIA,D.HORA,D.PERIODICIDAD
FROM DOCENCIA D, LOCALES L
WHERE ( (D.CURSO = 1) AND (L.CAPACIDAD > 100) AND (D.LOCAL = L.CODIGO) )
ORDER BY D.ID

/* Ejercicio 20 */
SELECT DISTINCT P.APELLIDO1, P.APELLIDO2, P.NOMBRE_PILA
FROM PROFESORES P, ASIGNATURAS A, DOCENCIA D
WHERE (A.NOMBRE = 'Bases de Datos') AND (P.CODIGO = D.PROFESOR) AND (A.SIGLAS = D.SIGLAS)
ORDER BY P.APELLIDO1, P.APELLIDO2, P.NOMBRE_PILA

/* Ejercicio 21 */
SELECT *
FROM DOCENCIA D, GRUPOS G, ASIGNATURAS A
WHERE (A.NOMBRE = 'Bases de Datos') AND (D.GRUPO = G.CODIGO) AND (A.SIGLAS = D.SIGLAS) AND (D.CLASE = G.CLASE) AND (D.CURSO = G.CURSO)


/* Ejercicio 22 */
SELECT DISTINCT P.NOMBRE_PILA, P.CODIGO, A.ALUMNOS, A.NOMBRE
FROM PROFESORES P, DOCENCIA D, ASIGNATURAS A
WHERE (P.CODIGO = D.PROFESOR) AND (A.SIGLAS = D.SIGLAS)
ORDER BY A.ALUMNOS DESC, P.CODIGO DESC

/* Ejercicio 23 */
SELECT UNIQUE A.SIGLAS, A.NOMBRE, L.NOMBRE, L.CAPACIDAD
FROM ASIGNATURAS A, LOCALES L, DOCENCIA D
WHERE (D.HORA BETWEEN 10 AND 15) AND (L.CAPACIDAD > 100) AND (D.LOCAL = L.CODIGO) AND (D.SIGLAS = A.SIGLAS)
ORDER BY A.SIGLAS, L.NOMBRE

/* Ejercicio 24 */
SELECT DISTINCT (P.CODIGO||'-'||P.NOMBRE_PILA) AS COD_NOMBRE
FROM PROFESORES P, AREAS A, DEPARTAMENTOS D
WHERE (P.ACTIVO = '1') AND (P.AREA = A.CODIGO) AND (D.NOMBRE LIKE '%nform%') AND (D.CODIGO = A.DEPARTAMENTO)

/* Ejercicio 25 */
SELECT DISTINCT DE.NOMBRE||'('||DE.CODIGO||')' AS NOMBRE_DEPARTEMENTO, G.NOMBRE
FROM DEPARTAMENTOS DE, DOCENCIA DO, GRUPOS G
WHERE (G.CODIGO = DO.GRUPO)





