/* Ejercicio 3*/
SELECT CODHOSP, NOMHOSP, NUMEMP
FROM HOSPITAL
WHERE CIUDAD='Pamplona'
;

/* Ejercicio 4*/
SELECT COUNT(H.CODHOSP) AS NºHOSPITALES
FROM HOSPITAL H
;

/* Ejercicio 5*/
SELECT COUNT(H.CODHOSP) AS NºHOSPITALES
FROM HOSPITAL H
WHERE H.NUMEMP>4
;

/* Ejercicio 6*/
SELECT *
FROM EMPLEADO
ORDER BY CUALIFICACION
;

/* Ejercicio 7*/
SELECT COUNT(CUALIFICACION)  
FROM EMPLEADO
WHERE CUALIFICACION='AUXILIAR'
;

/* Ejercicio 8*/
SELECT COUNT(*)
FROM EMPLEADO
WHERE CUALIFICACION='AUXILIAR' AND DEPAR='D3'
;

/* Ejercicio 9*/
SELECT H.NOMHOSP, COUNT(E.CUALIFICACION) AS AUXILIARES
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE E.DNI=T.DNI AND T.CODHOSP=H.CODHOSP AND CUALIFICACION='AUXILIAR' AND DEPAR='D3'
GROUP BY H.NOMHOSP
;

/* Ejercicio 10*/
SELECT E.DNI, E.NOMBRE, E.DEPAR
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.DEPAR=D.CODDEPT AND E.CUALIFICACION='DOCTOR' AND D.NOMDEPT='PEDIATRIA'
;

/* Ejercicio 11*/
SELECT E.DNI, E.AP1, E.SUELDO, H.CODHOSP
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE E.DNI=T.DNI AND T.CODHOSP=H.CODHOSP
;

/* Ejercicio 12*/
SELECT E.DNI, E.AP1, E.SUELDO, COUNT(H.CODHOSP) AS NºHOSPITALES
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE E.DNI=T.DNI AND T.CODHOSP=H.CODHOSP
GROUP BY E.DNI, E.AP1, E.SUELDO
ORDER BY NºHOSPITALES DESC
;

/* Ejercicio 13*/
SELECT COUNT(*)
FROM INGRESOS 
WHERE FECHA > '01/01/2018'
;

/* Ejercicio 14*/
SELECT COUNT(I.HISTORIAL) AS INGRESOS
FROM INGRESOS I, DEPHOSPITAL D, EMPLEADO E
WHERE I.FECHA>'01/01/2018' AND D.NOMDEPT='PEDIATRIA' AND I.DNI=E.DNI AND E.DEPAR=D.CODDEPT 
;

/* Ejercicio 15*/
SELECT I.HISTORIAL, I.DNI, I.CODHOSP, I.FECHA,  H.NOMHOSP, E.AP1
FROM EMPLEADO E, INGRESOS I, HOSPITAL H
WHERE I.DNI=E.DNI AND I.CODHOSP=H.CODHOSP 
;

/* Ejercicio 16*/
SELECT SUM(NUMEMP) TOTAL_EMPLEADOS
FROM HOSPITAL 
;

/* Ejercicio 17 Y 24*/
SELECT CODHOSP, NUMEMP
FROM HOSPITAL 
GROUP BY NUMEMP,CODHOSP
;
/*SELECT CODHOSP, NUMEMP
FROM HOSPITAL 
;*/

/* Ejercicio 18*/
SELECT MAX(SUELDO) AS MAX, MIN(SUELDO) AS MIN, AVG(SUELDO) AS MEDIA
FROM EMPLEADO
;

/* Ejercicio 19*/
SELECT MAX(E.SUELDO) AS MAX, MIN(E.SUELDO) AS MIN, AVG(E.SUELDO) AS MEDIA
FROM EMPLEADO E, PACIENTE P, INGRESOS I  
WHERE P.NOMBRE LIKE '%García%' AND I.HISTORIAL=P.HISTORIAL AND I.DNI=E.DNI
;

/* Ejercicio 20*/
SELECT MAX(E.SUELDO) AS MAX, MIN(E.SUELDO) AS MIN, AVG(E.SUELDO) AS MEDIA
FROM EMPLEADO E
WHERE E.DEPAR LIKE '%D3%'
;

/* Ejercicio 21*/
SELECT D.CODDEPT, AVG(E.SUELDO) AS MEDIA
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.DEPAR=D.CODDEPT
GROUP BY D.CODDEPT
ORDER BY D.CODDEPT
;

/* Ejercicio 22*/
SELECT D.CODDEPT, AVG(E.SUELDO) AS MEDIA
FROM DEPHOSPITAL D, EMPLEADO E
WHERE D.CODDEPT=E.DEPAR
GROUP BY D.CODDEPT
HAVING  AVG(E.SUELDO)>400
; 

/* Ejercicio 23*/
SELECT E.CUALIFICACION, SUM(E.SUELDO) AS TOTAL
FROM EMPLEADO E
GROUP BY E.CUALIFICACION
ORDER BY TOTAL DESC
;

/* Ejercicio 25*/
SELECT DISTINCT E.DNI
FROM EMPLEADO E, INGRESOS I
WHERE E.DNI=I.DNI
ORDER BY E.DNI
;

/* Ejercicio 26*/
SELECT I.CODHOSP, I.FECHA, E.AP1, E.DIRECCION, D.NOMDEPT
FROM EMPLEADO E, DEPHOSPITAL D, INGRESOS I, HOSPITAL H
WHERE E.DNI=I.DNI AND E.DEPAR=D.CODDEPT AND I.CODHOSP=H.CODHOSP
ORDER BY I.HISTORIAL
;

/* Ejercicio 27*/
SELECT COUNT(I.CODHOSP) AS NºINGRESOS, H.CIUDAD
FROM INGRESOS I, HOSPITAL H
WHERE I.CODHOSP=H.CODHOSP
GROUP BY H.CIUDAD
;

/* Ejercicio 28*/
SELECT E.DEPAR, COUNT(I.DNI) AS DEPARTAMENTOS
FROM INGRESOS I, EMPLEADO E
WHERE I.DNI=E.DNI AND I.FECHA>='31/12/2017'
GROUP BY E.DEPAR
;

/* Ejercicio 29*/
SELECT E.DEPAR, H.CIUDAD, COUNT(I.DNI) AS DEPARTAMENTOS
FROM INGRESOS I, HOSPITAL H, DEPHOSPITAL D, EMPLEADO E
WHERE I.DNI=E.DNI AND I.CODHOSP=H.CODHOSP AND E.DEPAR=D.CODDEPT AND I.FECHA>='31/12/2017'
GROUP BY E.DEPAR,H.CIUDAD
;

/* Ejercicio 30*/
SELECT P.NOMBRE, COUNT (P.HISTORIAL)
FROM PACIENTE P, INGRESOS I
WHERE P.HISTORIAL = I.HISTORIAL
GROUP BY P.NOMBRE
HAVING COUNT(P.HISTORIAL)>2
;









































