/*1*/

INSERT INTO PILOTO (CODPILOTO, NOMBRE, CODPAIS, FECHANACIMIENTO, LUGARNACIMIENTO, SEXO) VALUES ('ANDUZ', 'Asier Andueza', 'ES', '04/10/1999', 'Pamplona', 'H');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2017-18', 'ANDUZ', 'Aguri', 'PR');
commit;
/*2*/
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) 
VALUES ('2018-19', 'ANDUZ', 'Aguri', 'PR');

/*Da un error debido a que se está intentando introducir un 
set de datos con clave primaria repetida,
ya que se ha introducido previamente (codpiloto en este caso)*/

/*3*/
DELETE FROM CIRCUITO
WHERE NOMBRE = 'Autódromo Hermanos Rodríguez';

/*No deja debido a que NOMBRE en CIRCUITO es clave extranjera de CARRERA, 
luego al eliminarla la clave extranjera deja de tener sentido*/

/*4*/
SELECT T.SISTEMAPUNTOS
FROM TEMPORADA T, PERTENECE P 
WHERE P.PERIODO=T.PERIODO AND P.PERIODO>'2014-15';

/*5*/
SELECT P.NOMBRE, P.FECHANACIMIENTO, P.LUGARNACIMIENTO, PA.NOMBRE_ESP
FROM PILOTO P, PAIS PA
WHERE PA.CODPAIS = P.CODPAIS
ORDER BY FECHANACIMIENTO ASC;

/*6*/
SELECT PA.NOMBRE_ENG, COUNT(CI.NOMBRE) AS Total_circuitos
FROM PAIS PA, CIRCUITO CI
WHERE PA.CODPAIS=CI.CODPAIS
GROUP BY PA.NOMBRE_ENG
ORDER BY Total_circuitos DESC;

/*7*/
SELECT P.PERIODO, E.NOMBRE, PA.NOMBRE_ESP, COUNT(PI.CODPILOTO) AS Total_pilotos
FROM PERTENECE P, PILOTO PI, PAIS PA, EQUIPO E
WHERE E.CODPAIS=PA.CODPAIS AND E.NOMBRE=P.EQUIPO AND P.CODPILOTO=PI.CODPILOTO AND P.ROL<>'PR' 
GROUP BY P.PERIODO, E.NOMBRE, PA.NOMBRE_ESP;

/*8*/
SELECT P.PERIODO, E.NOMBRE, PA.NOMBRE_ESP, COUNT(PI.CODPILOTO) AS Total_pilotos
FROM PERTENECE P, PILOTO PI, PAIS PA, EQUIPO E
WHERE E.CODPAIS=PA.CODPAIS AND E.NOMBRE=P.EQUIPO AND P.CODPILOTO=PI.CODPILOTO AND P.ROL<>'PR' 
GROUP BY P.PERIODO, E.NOMBRE, PA.NOMBRE_ESP
HAVING COUNT (PI.CODPILOTO)>=2;

/*9*/
SELECT UNIQUE C.FECHACARRERA, C.NOMBRE_GP
FROM CARRERA C, PARTICIPA P, PILOTO PI
WHERE C.FECHACARRERA=P.FECHACARRERA AND C.VUELTAS>15 AND P.CODPILOTO=PI.CODPILOTO /*AND PI.NOMBRE'P'*/
ORDER BY C.FECHACARRERA DESC;

/*10*/
SELECT MIN(P.TIEMPOVUELTARAPIDA) AS Vuelta_mas_rapida
FROM PARTICIPA P;

/*11*/
SELECT PI.NOMBRE, MIN(P.TIEMPOVUELTARAPIDA) AS Vuelta_mas_rapida
FROM PILOTO PI, PARTICIPA P 
group by PI.NOMBRE
ORDER BY Vuelta_mas_rapida ASC;

/*12*/
SELECT ('Las carreras en el '||NOMBRE||' suelen tener una media de '||(LONGITUD/CURVAS)||' metros de recta entre curvas' ) 
FROM CIRCUITO;

/*13*/
SELECT CA.FECHACARRERA, CA.NOMBRE_GP, CA.CIRCUITO, CI.CURVAS*CA.VUELTAS
FROM CARRERA CA, CIRCUITO CI
WHERE CA.CIRCUITO=CI.NOMBRE AND CI.URBANO='S';
/*Se desea obtener un listado de las curvas totales de los circuitos
en el que se cumple que son circuitos urbanos, mostrando 
los siguientes datos: la fecha de la carrera y el nombre del GP (gran premio) */

/*14*/
SELECT PI.NOMBRE, COUNT(P.POSICION_LLEGADA) AS GANADAS
FROM PILOTO PI, PARTICIPA P
WHERE P.CODPILOTO=PI.CODPILOTO AND P.POSICION_LLEGADA=1
GROUP BY PI.NOMBRE
HAVING COUNT(P.POSICION_LLEGADA)>1;

/*15*/
SELECT P.FECHACARRERA, CA.NOMBRE_GP, PI.NOMBRE, PA.NOMBRE_ESP, P.POSICION_SALIDA-P.POSICION_LLEGADA AS REMONTADOS
FROM PARTICIPA P, CARRERA CA, PILOTO PI, PAIS PA
WHERE P.FECHACARRERA=CA.FECHACARRERA 
AND P.CODPILOTO=PI.CODPILOTO 
AND PI.CODPAIS=PA.CODPAIS 
AND (P.POSICION_SALIDA-P.POSICION_LLEGADA)>0
ORDER BY REMONTADOS ASC;

/*16*/
SELECT unique PI.NOMBRE, PA.NOMBRE_ESP AS Pais_piloto, E.NOMBRE, E.CODPAIS AS Pais_equipo
FROM PILOTO PI, PAIS PA, EQUIPO E
WHERE PA.CODPAIS = PI.CODPAIS;
