/*6*/
SELECT D.ID,D.PROFESOR,D.SIGLAS,A.ANUALIDAD,A.CREDITOS
FROM ASIGNATURAS A,DOCENCIA D
WHERE D.SIGLAS=A.SIGLAS;
/*7*/
SELECT *
FROM ASIGNATURAS A
WHERE (A.HORAS_TEORIA>0) AND (A.HORAS_PRACTICA>0);
/*8*/
SELECT *
FROM ASIGNATURAS A
WHERE (A.HORAS_TEORIA>0) OR (A.HORAS_PRACTICA>0);
/*9*/
SELECT *
FROM ASIGNATURAS A
WHERE ((A.HORAS_TEORIA>0) OR (A.HORAS_PRACTICA>0)) AND A.ALUMNOS>30;
/*10*/
SELECT DISTINCT GRUPO
FROM DOCENCIA;
/*11*/
SELECT SIGLAS,ALUMNOS
FROM ASIGNATURAS
WHERE ANUALIDAD='A';
/*12*/
SELECT *
FROM LOCALES
WHERE EDIFICIO LIKE 'E%';
/*13*/
SELECT *
FROM LOCALES
WHERE CAPACIDAD BETWEEN 30 AND 80;
/*14*/
SELECT *
FROM LOCALES
WHERE SITUACION NOT LIKE 'Planta Primera%';
/*15*/
SELECT SIGLAS,NOMBRE,CREDITOS,CURSO,ANUALIDAD,CLASE,HORAS_TEORIA,GRUPOS_PRACTICA,GRUPOS_TEORIA,ALUMNOS,(HORAS_PRACTICA*1.1) AS "Previsión Profesorado"
FROM ASIGNATURAS
WHERE HORAS_PRACTICA>0;
/*16*/
SELECT 'El área de código '||A.CODIGO||' pertenece al departamento '|| A.DEPARTAMENTO
FROM AREAS A;
/*17*/
SELECT DISTINCT ||CODIGO'-' APELLIDO1',' APELLIDO2, NOMBRE_PILA
FROM PROFESORES;
/*18*/
SELECT DISTINCT D.CODIGO,A.CODIGO,A.NOMBRE
FROM DEPARTAMENTOS D,AREAS A
WHERE A.DEPARTAMENTO=D.CODIGO
ORDER BY D.CODIGO,A.CODIGO;
/*19*/
SELECT D.ID,D.CURSO,D.CLASE,D.GRUPO,D.SIGLAS,D.PROFESOR,D.LOCAL,D.DIA,D.HORA,D.PERIODICIDAD
FROM DOCENCIA D,LOCALES
WHERE D.CURSO=1 AND LOCALES.CAPACIDAD>100;
/*20*/
SELECT DISTINCT P.APELLIDO1,P.APELLIDO2,P.NOMBRE_PILA
FROM PROFESORES P,ASIGNATURAS,DOCENCIA 
WHERE (ASIGNATURAS.NOMBRE='Bases de Datos') AND (P.CODIGO=DOCENCIA.PROFESOR) AND (ASIGNATURAS.SIGLAS=DOCENCIA.SIGLAS);
/*21*/
SELECT DISTINCT D.ID,D.CURSO,D.CLASE,D.GRUPO,D.SIGLAS,D.PROFESOR,D.LOCAL,D.DIA,D.HORA,D.PERIODICIDAD,G.CURSO,G.CLASE,G.CODIGO
FROM ASIGNATURAS A,DOCENCIA D,GRUPOS G
WHERE (A.NOMBRE='Bases de Datos') AND (D.CLASE=G.CLASE) AND (D.SIGLAS=A.SIGLAS);
/*22*/
SELECT DISTINCT P.CODIGO,P.NOMBRE_PILA,A.NOMBRE,A.ALUMNOS
FROM PROFESORES P,ASIGNATURAS A,DOCENCIA D
WHERE D.SIGLAS=A.SIGLAS AND D.PROFESOR=P.CODIGO
ORDER BY A.ALUMNOS;
/*23*/
SELECT DISTINCT A.SIGLAS,A.NOMBRE,L.CAPACIDAD,L.NOMBRE
FROM ASIGNATURAS A,LOCALES L,DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS AND D.LOCAL=L.CODIGO AND L.CAPACIDAD>100 AND (D.HORA BETWEEN 10 AND 15);
/*24*/
SELECT (P.CODIGO||'-'||P.NOMBRE_PILA) AS COD_NOMBRE
FROM PROFESORES P,AREAS A,DEPARTAMENTOS D
WHERE P.ACTIVO='1' AND A.NOMBRE LIKE '%nform%' AND A.CODIGO=P.AREA AND D.CODIGO=A.DEPARTAMENTO;
/*25*/
SELECT DISTINCT (D.NOMBRE||'('||D.CODIGO||')') AS NOMBRE_DEPARTAMENTO, G.NOMBRE
FROM DEPARTAMENTOS D,AREAS A,PROFESORES P,GRUPOS G,DOCENCIA DO
WHERE D.CODIGO=A.DEPARTAMENTO AND A.CODIGO=P.AREA AND P.CODIGO=DO.PROFESOR AND DO.CLASE=G.CLASE;
/*26*/
SELECT DISTINCT A.SIGLAS,A.NOMBRE,D.DIA,D.HORA,L.CODIGO,L.NOMBRE
FROM ASIGNATURAS A, LOCALES L, DOCENCIA D
WHERE ((A.ANUALIDAD='(null)') OR (A.SIGLAS IN ('ACo','BDa','DES','Eco','Fis-G'))) AND (A.SIGLAS=D.SIGLAS) AND (L.CODIGO=D.LOCAL)
ORDER BY A.SIGLAS,D.DIA DESC,D.HORA DESC;
/*27*/
SELECT DISTINCT A.NOMBRE,G.NOMBRE,(A.ALUMNOS/A.GRUPOS_TEORIA) AS AlumnosxGrupo
FROM ASIGNATURAS A, GRUPOS G, DOCENCIA D
WHERE (A.SIGLAS=D.SIGLAS) AND (D.CLASE=G.CLASE) AND (G.CLASE='P') AND (D.HORA NOT BETWEEN (11.3) AND (19.3))
ORDER BY AlumnosxGrupo DESC, A.NOMBRE,G.NOMBRE;