CREATE TABLE CLIENTE(
COD_CLIENTE NUMBER(10) UNIQUE,
NOMBRE VARCHAR(15) NOT NULL,
DIRECCION VARCHAR(20) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
TIPO VARCHAR(1) NOT NULL,
CONSTRAINT CHECKTIPO CHECK (TIPO IN ('E','B','N')),
CONSTRAINT CODIGOCLIENTE PRIMARY KEY (COD_CLIENTE));

CREATE TABLE ORDEN(
FECHA_PETICION DATE NOT NULL,
FECHA_ENVIO DATE NOT NULL,
FORMA_PAGO VARCHAR(1) NOT NULL,
NUM_ORDEN NUMBER(10) UNIQUE
CONSTRAINT CHECKPAGO CHECK (FORMA_PAGO IN ('A','C','G')),
CONSTRAINT FECHAS CHECK (FECHA_ENVIO>FECHA_PETICION),
CONSTRAINT COD_ORDEN PRIMARY KEY (NUM_ORDEN));

CREATE TABLE ARTICULO(
COD_ARTICULO NUMBER(9),
DESCRIPCION_ART VARCHAR(100),
CANTIDAD NUMBER(5),
MAQ_ARTICULO NUMBER(10),
CONSTRAINT CHECK_ART PRIMARY KEY (COD_ARTICULO),
CONSTRAINT FK3 FOREIGN KEY (MAQ_ARTICULO) REFERENCES MAQUINA(COD_MAQUINA));

CREATE TABLE MAQUINA(
COD_MAQUINA NUMBER(10),
DESCRIPCION_MAQ VARCHAR(100),
SITUACION VARCHAR (20),
CONSTRAINT CHECK_MAQ PRIMARY KEY (COD_MAQUINA));

CREATE TABLE RAL(
VERDE NUMBER (3,2) NOT NULL,
ROJO NUMBER (3,2) NOT NULL,
AZUL NUMBER (3,2) NOT NULL,
COD_RAL NUMBER(5),
CONSTRAINT CHECK_RAL PRIMARY KEY (COD_RAL));

CREATE TABLE CONTIENE(
CONTIENE_ORDEN NUMBER(10),
CONTIENE_ARTICULO NUMBER(9),
CONTIENE_RAL NUMBER(5),
CANTIDAD NUMBER(4),
CONSTRAINT FK4 FOREIGN KEY (CONTIENE_ORDEN) REFERENCES ORDEN(NUM_ORDEN),
CONSTRAINT FK5 FOREIGN KEY (CONTIENE_ARTICULO) REFERENCES ARTICULO(COD_ARTICULO),
CONSTRAINT FK6 FOREIGN KEY (CONTIENE_RAL) REFERENCES RAL(COD_RAL),
CONSTRAINT CHECK_CONTIENE PRIMARY KEY (CONTIENE_ORDEN, CONTIENE_ARTICULO,CONTIENE_RAL));

CREATE TABLE PRODUCCION(
CANTIDAD_BIEN NUMBER(5),
CANTIDAD_MAL NUMBER(5),
TIEMPO NUMBER(5),
FECHA DATE, 
COD_PRODUCCIONA NUMBER(9),
COD_PRODUCCIONM NUMBER(10),
CONSTRAINT FK7 FOREIGN KEY (COD_PRODUCCIONA) REFERENCES ARTICULO(COD_ARTICULO),
CONSTRAINT FK8 FOREIGN KEY (COD_PRODUCCIONM) REFERENCES MAQUINA(COD_MAQUINA),
CONSTRAINT CHECK_PRODUCCION PRIMARY KEY (COD_PRODUCCIONA,COD_PRODUCCIONM));

