/*1*/
SELECT COUNT(*)
FROM ASIGNATURAS;
/*2*/
SELECT COUNT(*)NUMANUALES 
FROM ASIGNATURAS
WHERE ANUALIDAD='A';
/*3*/
SELECT MAX(ALUMNOS) MAXALUMNOS
FROM ASIGNATURAS;
/*4*/
SELECT AVG(ALUMNOS)
FROM ASIGNATURAS;
/*5*/
SELECT SUM(ALUMNOS)
FROM ASIGNATURAS;
/*6*/
SELECT PROFESOR,COUNT(*) DOCENCIA
FROM DOCENCIA 
GROUP BY PROFESOR
ORDER BY PROFESOR;
/*7*/
SELECT PROFESOR,COUNT(*) 
FROM DOCENCIA 
GROUP BY PROFESOR  
HAVING COUNT(*)>10; 
/*8*/
SELECT SUM(A.HORAS_TEORIA)TOTALHORASTEORIA ,SUM(A.HORAS_PRACTICA)TOTALHORASPRACTICA 
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS;
/*9*/
SELECT SUM(A.HORAS_TEORIA)TOTALHORASTEORIA ,SUM(A.HORAS_PRACTICA)TOTALHORASPRACTICA 
FROM ASIGNATURAS A, DOCENCIA D
WHERE ANUALIDAD='A' AND A.SIGLAS=D.SIGLAS AND D.PROFESOR>30;
/*10*/
SELECT COUNT(*)NUMASIG, AVG(HORAS_PRACTICA)
FROM ASIGNATURAS A, DOCENCIA D
WHERE D.PROFESOR>30 AND A.SIGLAS=D.SIGLAS AND A.ANUALIDAD='A';
/*11*/
SELECT MAX(CAPACIDAD)MAXCAPACIDAD 
FROM LOCALES;
/*12*/
SELECT MAX(L.CAPACIDAD)MAXCAPACIDAD 
FROM LOCALES L, DOCENCIA D, ASIGNATURAS A
WHERE A.HORAS_PRACTICA>0 AND A.SIGLAS=D.SIGLAS AND L.CODIGO=D.LOCAL;
/*13*/
SELECT COUNT(*)LOCALES1  
FROM LOCALES L
WHERE L.SITUACION LIKE 'Planta Primera%';
/*14*/
SELECT SITUACION, COUNT(*)
FROM LOCALES
GROUP BY SITUACION;
/*15*/
SELECT MAX(HORA)ULTIMA_HORA ,MIN(HORA)PRIMERA_HORA 
FROM DOCENCIA
GROUP BY DIA;
/*16*/
SELECT ANUALIDAD, COUNT(*)NUM_ASIGNATURAS , AVG(CREDITOS)MEDIA_CREDITOS ,MIN(ALUMNOS)
FROM ASIGNATURAS
WHERE ANUALIDAD NOT IN 'A' OR ANUALIDAD IS NULL
GROUP BY ANUALIDAD;
/*17*/
SELECT A.SIGLAS, A.NOMBRE
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS
GROUP BY A.SIGLAS, A.NOMBRE
HAVING COUNT (D.ID) BETWEEN 10 AND 20;
/*18*/
SELECT D.HORA, COUNT(D.DIA)NUM_DIAS 
FROM DOCENCIA D, ASIGNATURAS A
WHERE  A.SIGLAS=D.SIGLAS AND A.NOMBRE='Algebra'
GROUP BY D.HORA
HAVING COUNT(D.DIA)>=2;
/*19*/
SELECT D.CURSO, MAX (A.ALUMNOS),MIN (A.ALUMNOS), AVG(A.ALUMNOS)
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS 
GROUP BY D.CURSO;
/*20*/
SELECT L.NOMBRE,L.EDIFICIO,MAX(D.CURSO)
FROM LOCALES L, DOCENCIA D
WHERE L.CODIGO=D.LOCAL
GROUP BY L.NOMBRE,L.EDIFICIO
ORDER BY L.NOMBRE;
/*21*/
SELECT A.CURSO, A.NOMBRE ||'('||A.SIGLAS||')'ASIGNATURA, COUNT (A.GRUPOS_TEORIA),COUNT (A.GRUPOS_PRACTICA)
FROM ASIGNATURAS A
GROUP BY A.CURSO, A.NOMBRE,A.SIGLAS
ORDER BY A.CURSO,A.NOMBRE;
/*22*/
SELECT A.NOMBRE, D.DIA, COUNT(DISTINCT P.CODIGO)PROFESORES_NO_TIEMPO_COMPLETO 
FROM ASIGNATURAS A,DOCENCIA D,PROFESORES P
WHERE A.SIGLAS=D.SIGLAS AND D.PROFESOR=P.CODIGO AND  P.DEDICACION NOT LIKE '%TC%'
GROUP BY A.NOMBRE,D.DIA
HAVING COUNT(DISTINCT P.CODIGO)>1;
/*23*/
SELECT A.CURSO, A.NOMBRE ||'('||A.SIGLAS||')'ASIGNATURA,COUNT (A.GRUPOS_TEORIA),COUNT (A.GRUPOS_PRACTICA)
FROM ASIGNATURAS A
WHERE A.CREDITOS>9 AND A.GRUPOS_TEORIA>0 AND A.GRUPOS_PRACTICA>0
GROUP BY A.CURSO, A.NOMBRE,A.SIGLAS
ORDER BY A.CURSO,A.NOMBRE;
/*24*/
SELECT A.NOMBRE ||'('||A.SIGLAS||')'ASIGNATURA,(A.ALUMNOS/COUNT(*))ALUMNOS_POR_CLASE
FROM ASIGNATURAS A,DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS
GROUP BY A.NOMBRE,A.SIGLAS,A.ALUMNOS
ORDER BY ALUMNOS_POR_CLASE DESC;
/*25*/
SELECT COUNT(DISTINCT  D.PROFESOR),G.NOMBRE
FROM DOCENCIA D,GRUPOS G
WHERE D.CLASE=G.CLASE AND D.CURSO=G.CURSO AND D.GRUPO=G.CODIGO
GROUP BY G.NOMBRE;
/*26*/
SELECT G.NOMBRE
FROM DOCENCIA D,GRUPOS G
WHERE  D.CLASE=G.CLASE AND D.CURSO=G.CURSO AND D.GRUPO=G.CODIGO
GROUP BY G.NOMBRE
HAVING COUNT (DISTINCT D.PROFESOR)=1;
/*27*/
SELECT COUNT(D.SIGLAS),(P.APELLIDO1||P.APELLIDO2|| ','||P.NOMBRE_PILA) NOMBRE_Y_APELLIDOS 
FROM DOCENCIA D, PROFESORES P
WHERE D.PROFESOR=P.CODIGO
GROUP BY P.APELLIDO1,P.APELLIDO2,P.NOMBRE_PILA;
/*28*/
SELECT (P.APELLIDO1||P.APELLIDO2|| ','||P.NOMBRE_PILA) NOMBRE_Y_APELLIDOS 
FROM DOCENCIA D, PROFESORES P
WHERE D.PROFESOR=P.CODIGO
GROUP BY P.APELLIDO1,P.APELLIDO2,P.NOMBRE_PILA
HAVING COUNT (DISTINCT D.SIGLAS)>1;
/*29*/
SELECT L.NOMBRE,L.EDIFICIO,A.NOMBRE,D.CLASE,(L.CAPACIDAD-(A.ALUMNOS)/COUNT(*))DIFERENCIA_ALUMNOS_X_CLASE 
FROM LOCALES L,ASIGNATURAS A, DOCENCIA D
WHERE L.CODIGO=D.LOCAL AND A.SIGLAS=D.SIGLAS AND A.HORAS_PRACTICA>0
GROUP BY L.NOMBRE,L.EDIFICIO,A.NOMBRE,D.CLASE,L.CAPACIDAD,A.ALUMNOS
HAVING (L.CAPACIDAD-(A.ALUMNOS)/COUNT(*))<1;