
CREATE TABLE USUARIO(
NOMBRE VARCHAR(15) NOT NULL,
APELLIDO VARCHAR(15) NOT NULL,
DIRECCION VARCHAR(20) NOT NULL,
SEXO VARCHAR(1) NOT NULL, 
EDAD NUMBER(3),
CODIGO NUMBER(6),
CONSTRAINT COD_USUARIO PRIMARY KEY (CODIGO),
CONSTRAINT EDAD_MIN CHECK (EDAD>15),
CONSTRAINT CHECKS CHECK (SEXO IN ('M','F','O')));

CREATE TABLE CLASES(
LETRA VARCHAR(1),
COD_TIEMPO VARCHAR(1) NOT NULL,
TIEMPO NUMBER(3),
CONSTRAINT CHECK_LETRA PRIMARY KEY (LETRA));


CREATE TABLE LIBRO(
TITULO VARCHAR(20) UNIQUE,
AUTOR VARCHAR(20) NOT NULL,
ISBN VARCHAR(20),
EDITORIAL VARCHAR(15),
CLASIFICACION VARCHAR(1) NOT NULL,
CONSTRAINT COD_LIBRO PRIMARY KEY (ISBN),
CONSTRAINT VAL CHECK (CLASIFICACION IN ('A','B','C','D','E')),
CONSTRAINT FK3 FOREIGN KEY(CLASIFICACION) REFERENCES CLASES(LETRA));


CREATE TABLE PRESTAMO(
COD_PRESTAMO NUMBER(5) DEFAULT 0,
FECHA_PRES DATE NOT NULL,
FECHA_DEV DATE NOT NULL,
COD_USUARIO NUMBER(6),
COD_LIBRO VARCHAR(20),
CONSTRAINT CHECK_PRESTAMO PRIMARY KEY (COD_PRESTAMO),
CONSTRAINT CHECKFECHA CHECK (FECHA_DEV>FECHA_PRES),
CONSTRAINT FK1 FOREIGN KEY(COD_USUARIO) REFERENCES USUARIO(CODIGO),
CONSTRAINT FK2 FOREIGN KEY(COD_LIBRO) REFERENCES LIBRO(ISBN));
