CREATE TABLE USUARIO(
COD NUMBER(10),
NOMBRE VARCHAR(15) NOT NULL,
APELLIDO VARCHAR(15) NOT NULL,
EDAD NUMBER(2),
SEXO VARCHAR(1), 
CONSTRAINT COD_USUARIO PRIMARY KEY (COD),
CONSTRAINT EDAD_MIN CHECK (EDAD>15),
CONSTRAINT CHECKS CHECK (SEXO IN ('M','F','O')));


CREATE TABLE LIBRO(
ISBN VARCHAR(10),
CLASE VARCHAR(1) NOT NULL,
TITULO VARCHAR(32) UNIQUE,
AUTOR VARCHAR(15) NOT NULL,
EDITORIAL VARCHAR(25),
CONSTRAINT COD_LIBRO PRIMARY KEY (ISBN),
CONSTRAINT VAL CHECK (CLASE IN ('A','B','C','D','E')),
CONSTRAINT FK3 FOREIGN KEY(CLASE) REFERENCES CLASELIBRO(CLASE));

CREATE TABLE CLASELIBRO(
CLASE VARCHAR(1) NOT NULL,
TIEMPO NUMBER(5),
CONSTRAINT CHECK_LETRA PRIMARY KEY (CLASE));


CREATE TABLE PRESTAMO(
ISBN VARCHAR(10),
COD NUMBER(10),
FECHA_INI DATE,
FECHA_DEV DATE,
CONSTRAINT CHECKDATE CHECK (FECHA_INI<FECHA_DEV),
CONSTRAINT DNIC PRIMARY KEY (ISBN, COD, FECHA_INI),
CONSTRAINT CLAVE_US FOREIGN KEY (COD) REFERENCES USUARIO(COD));


/*4*/

SELECT L.EDITORIAL, COUNT(L.ISBN) VOLUMENES
FROM LIBRO L
GROUP BY L.EDITORIAL
ORDER BY VOLUMENES DESC;

/*5*/

SELECT L.EDITORIAL, COUNT(L.ISBN) PRESTAMOS
FROM LIBRO L, PRESTAMO P
WHERE L.ISBN=P.ISBN
GROUP BY L.EDITORIAL
ORDER BY PRESTAMOS DESC;

/*6*/

SELECT COUNT(*)PRESTAMOS_TOTALES
FROM PRESTAMO;

/*7*/

SELECT U.COD, U.NOMBRE, U.EDAD, COUNT(P.ISBN)
FROM USUARIO U, PRESTAMO P
WHERE U.COD=P.COD AND U.EDAD BETWEEN 20 AND 30
GROUP BY U.COD, U.NOMBRE, U.EDAD
HAVING COUNT(P.ISBN)>1
ORDER BY U.COD;

/*8*/

SELECT U.COD, U.NOMBRE, U.EDAD,L.EDITORIAL, COUNT(P.ISBN)
FROM USUARIO U, PRESTAMO P, LIBRO L
WHERE U.COD=P.COD AND L.ISBN=P.ISBN
GROUP BY U.COD, U.NOMBRE, U.EDAD, L.EDITORIAL
HAVING COUNT(P.ISBN)>2;

/*9*/

SELECT L.ISBN,L.TITULO, L.AUTOR,P.FECHA_INI, FECHA_DEV
FROM LIBRO L, PRESTAMO P
WHERE L.ISBN=P.ISBN AND P.FECHA_DEV IS NULL;

/*10*/

SELECT L.ISBN
FROM LIBRO L, PRESTAMO P
WHERE L.ISBN=P.ISBN AND P.FECHA_DEV IS NULL
GROUP BY L.ISBN
HAVING COUNT(L.ISBN)>1;

/*11*/

SELECT U.COD, U.NOMBRE, U.APELLIDO, L.TITULO, C.TIEMPO, (P.FECHA_DEV-P.FECHA_INI)DIAS_PRESTAMO, ((P.FECHA_DEV-P.FECHA_INI)-C.TIEMPO) EXCEDIDOS
FROM USUARIO U, LIBRO L, PRESTAMO P, CLASELIBRO C
WHERE U.COD=P.COD AND P.ISBN=L.ISBN AND L.CLASE=C.CLASE AND P.FECHA_DEV IS NOT NULL
ORDER BY EXCEDIDOS DESC;

/*12*/

SELECT U.COD, U.NOMBRE, U.APELLIDO, L.TITULO, C.TIEMPO, SYSDATE, (SYSDATE-P.FECHA_INI)DIAS_PRESTAMO, ((SYSDATE-P.FECHA_INI)-C.TIEMPO) EXCEDIDOS
FROM USUARIO U, LIBRO L, PRESTAMO P, CLASELIBRO C
WHERE U.COD=P.COD AND P.ISBN=L.ISBN AND L.CLASE=C.CLASE AND P.FECHA_DEV IS NULL;
/*13*/

SELECT COUNT(L.AUTOR) AUTORES
FROM LIBRO L
WHERE L.AUTOR LIKE '_____';

/*14*/

SELECT L.EDITORIAL, SUM(C.TIEMPO) TIEMPO_TOTAL
FROM LIBRO L, CLASELIBRO C
WHERE L.CLASE=C.CLASE
GROUP BY L.EDITORIAL
ORDER BY TIEMPO_TOTAL;