/*1*/
/*2*/
SELECT ALL *
FROM HOSPITAL,DEPHOSPITAL,EMPLEADO,TRABAJA,PACIENTE,INGRESOS;
/*3*/
SELECT H.CODHOSP, H.NOMHOSP, H.NUMEMP
FROM HOSPITAL H
WHERE CIUDAD='Pamplona';
/*4*/
SELECT COUNT(H.CODHOSP)
FROM HOSPITAL H;
/*5*/
SELECT COUNT(H.CODHOSP)
FROM HOSPITAL H
WHERE H.NUMEMP>400;
/*6*/
SELECT *
FROM EMPLEADO
ORDER BY CUALIFICACION;
/*7*/
SELECT COUNT(E.DNI)TOT_AUXILIARES 
FROM EMPLEADO E
WHERE CUALIFICACION='AUXILIAR';
/*8*/
SELECT COUNT(E.DNI)TOT_AUXILIARES 
FROM EMPLEADO E, DEPHOSPITAL D
WHERE CUALIFICACION='AUXILIAR' AND E.DEPAR=D.CODDEPT AND CODDEPT='D3';
/*9*/
SELECT COUNT(E.DNI)TOT_AUXILIARES, H.NOMHOSP 
FROM EMPLEADO E, DEPHOSPITAL D, HOSPITAL H,TRABAJA T
WHERE CUALIFICACION='AUXILIAR' AND E.DEPAR=D.CODDEPT AND CODDEPT='D3' AND T.CODHOSP=H.CODHOSP AND T.DNI=E.DNI
GROUP BY H.NOMHOSP;
/*10*/
SELECT E.DNI,E.NOMBRE,D.CODDEPT
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.DEPAR=D.CODDEPT AND E.CUALIFICACION='DOCTOR' AND D.NOMDEPT='PEDIATRIA';
/*11*/
SELECT E.DNI,E.AP1,E.AP2,E.SUELDO,H.CODHOSP
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE T.CODHOSP=H.CODHOSP AND T.DNI=E.DNI;
/*12*/
SELECT E.DNI,E.AP1,E.AP2,E.SUELDO,COUNT(H.CODHOSP)NUM_HOSP 
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE T.CODHOSP=H.CODHOSP AND T.DNI=E.DNI
GROUP BY E.DNI,E.AP1,E.AP2,E.SUELDO
ORDER BY NUM_HOSP DESC;
/*13*/
SELECT COUNT(I.HISTORIAL)
FROM INGRESOS I
WHERE I.FECHA>'01/01/2016';
/*14*/
SELECT COUNT(I.HISTORIAL)
FROM INGRESOS I, EMPLEADO E, DEPHOSPITAL D
WHERE I.FECHA>'01/01/2016' AND E.DNI=I.DNI AND E.DEPAR=D.CODDEPT AND D.NOMDEPT='PEDIATRIA';
/*15*/
SELECT I.*, E.AP1,H.NOMHOSP
FROM INGRESOS I, HOSPITAL H,EMPLEADO E
WHERE I.CODHOSP=H.CODHOSP AND E.DNI=I.DNI;
/*16*/
SELECT SUM(H.NUMEMP)
FROM HOSPITAL H;
/*17*/
SELECT SUM(H.NUMEMP),H.CODHOSP
FROM HOSPITAL H
GROUP BY H.CODHOSP;
/*18*/
SELECT MAX(E.SUELDO)MAXIMO , MIN(E.SUELDO), AVG(E.SUELDO)MEDIA 
FROM EMPLEADO E;
/*19*/
SELECT MAX(E.SUELDO)MAXIMO , MIN(E.SUELDO), AVG(E.SUELDO)MEDIA 
FROM EMPLEADO E, INGRESOS I, PACIENTE P
WHERE P.NOMBRE='García' AND E.DNI=I.DNI AND I.HISTORIAL=P.HISTORIAL;
/*20*/
SELECT MAX(E.SUELDO)MAXIMO , MIN(E.SUELDO), AVG(E.SUELDO)MEDIA 
FROM EMPLEADO E, DEPHOSPITAL D
WHERE D.CODDEPT='D3' AND E.DEPAR=D.CODDEPT;
/*21*/
SELECT D.CODDEPT,AVG(E.SUELDO)
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.DEPAR=D.CODDEPT
GROUP BY D.CODDEPT;
/*22*/
SELECT D.CODDEPT,AVG(E.SUELDO)SUELDO_MEDIO 
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.DEPAR=D.CODDEPT
GROUP BY D.CODDEPT
HAVING AVG(E.SUELDO)>400;
/*23*/
SELECT SUM(E.SUELDO) TOTAL_SALARIOS,E.CUALIFICACION 
FROM EMPLEADO E
GROUP BY E.CUALIFICACION
ORDER BY TOTAL_SALARIOS DESC;
/*24*/
SELECT COUNT(E.DNI), H.NOMHOSP
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE T.CODHOSP=H.CODHOSP AND T.DNI=E.DNI
GROUP BY H.NOMHOSP;
/*25*/
SELECT DISTINCT I.DNI
FROM INGRESOS I;
/*26*/
SELECT I.HISTORIAL, I.CODHOSP CODH, I.FECHA,H.NOMHOSP HOSPITAL, E.AP1,E.DIRECCION,D.NOMDEPT
FROM EMPLEADO E, DEPHOSPITAL D,INGRESOS I,HOSPITAL H
WHERE E.DEPAR=D.CODDEPT AND E.DNI=I.DNI AND I.CODHOSP=H.CODHOSP;
/*27*/
SELECT H.CIUDAD, COUNT(I.HISTORIAL)
FROM INGRESOS I,HOSPITAL H
WHERE I.CODHOSP=H.CODHOSP
GROUP BY H.CIUDAD;
/*28*/
SELECT COUNT(I.HISTORIAL), D.NOMDEPT
FROM INGRESOS I, EMPLEADO E, DEPHOSPITAL D
WHERE I.FECHA>'31/12/2015' AND E.DNI=I.DNI AND E.DEPAR=D.CODDEPT
GROUP BY D.NOMDEPT;
/*29*/
SELECT COUNT(I.HISTORIAL), H.CIUDAD,D.NOMDEPT
FROM INGRESOS I, EMPLEADO E, DEPHOSPITAL D, HOSPITAL H
WHERE I.FECHA>'31/12/2015' AND E.DNI=I.DNI AND E.DEPAR=D.CODDEPT AND I.CODHOSP=H.CODHOSP
GROUP BY D.NOMDEPT,H.CIUDAD;
/*30*/
SELECT P.NOMBRE,COUNT(I.HISTORIAL)VISITAS 
FROM PACIENTE P, INGRESOS I
WHERE I.HISTORIAL=P.HISTORIAL
GROUP BY P.NOMBRE
HAVING COUNT(I.HISTORIAL)>2;