-- FORMULA E BD --

-- TEMPORADA DE FORMULA E
CREATE TABLE TEMPORADA 
(
  PERIODO VARCHAR2(7 CHAR) NOT NULL,
  SISTEMAPUNTOS VARCHAR2(50 CHAR) NOT NULL,
  NUMEROCARRERAS NUMBER NOT NULL, 
  CONSTRAINT TEMPORADA_PK PRIMARY KEY (PERIODO)
);

INSERT INTO TEMPORADA (PERIODO, SISTEMAPUNTOS, NUMEROCARRERAS) VALUES ('2016-17', '(25, 18, 15, 12, 10, 8, 6, 4, 3, 2)',2);
INSERT INTO TEMPORADA (PERIODO, SISTEMAPUNTOS, NUMEROCARRERAS) VALUES ('2017-18', '(25, 18, 15, 12, 10, 8, 6, 4, 2, 1)',2);

-- PAISES
CREATE TABLE PAIS
(
  CODPAIS CHAR(2) NOT NULL,
  NOMBRE_ESP VARCHAR2(100 CHAR) NOT NULL,
  NOMBRE_ENG VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT PAIS_PK PRIMARY KEY (CODPAIS)
);

INSERT INTO PAIS (CODPAIS, NOMBRE_ESP, NOMBRE_ENG) VALUES ('CH', 'China', 'China');
INSERT INTO PAIS (CODPAIS, NOMBRE_ESP, NOMBRE_ENG) VALUES ('ME', 'Mejico', 'Mexico');
INSERT INTO PAIS (CODPAIS, NOMBRE_ESP, NOMBRE_ENG) VALUES ('AL', 'Alemania', 'Germany');
INSERT INTO PAIS (CODPAIS, NOMBRE_ESP, NOMBRE_ENG) VALUES ('FR', 'Francia', 'France');
INSERT INTO PAIS (CODPAIS, NOMBRE_ESP, NOMBRE_ENG) VALUES ('SU', 'Suiza', 'Switzerland');
INSERT INTO PAIS (CODPAIS, NOMBRE_ESP, NOMBRE_ENG) VALUES ('JA', 'Japon', 'Japan');
INSERT INTO PAIS (CODPAIS, NOMBRE_ESP, NOMBRE_ENG) VALUES ('UK', 'Reino Unido', 'United Kingdom');
INSERT INTO PAIS (CODPAIS, NOMBRE_ESP, NOMBRE_ENG) VALUES ('BR', 'Brasil', 'Brazil');
INSERT INTO PAIS (CODPAIS, NOMBRE_ESP, NOMBRE_ENG) VALUES ('ES', 'España', 'Spain');

-- CIRCUITOS
CREATE TABLE CIRCUITO (
  NOMBRE VARCHAR2(50 CHAR) NOT NULL, 
  LONGITUD NUMBER NOT NULL, 
  CURVAS NUMBER NOT NULL, 
  CIUDAD VARCHAR2(50 CHAR) NOT NULL, 
  URBANO VARCHAR2(4 CHAR) NOT NULL, 
  CODPAIS CHAR(2) NOT NULL, 
  CONSTRAINT URBANO_CHK CHECK (URBANO IN ('S', 'N', 'SEMI')),
  CONSTRAINT CIRCUITO_PK PRIMARY KEY (NOMBRE),
  CONSTRAINT CIRCUITO_PAIS_FK FOREIGN KEY (CODPAIS) REFERENCES PAIS (CODPAIS)
);

INSERT INTO CIRCUITO (NOMBRE, LONGITUD, CURVAS, CIUDAD, URBANO, CODPAIS) VALUES ('Circuito del Parque Olímpico de Pekín', 3440, 20, 'Pekin', 'S', 'CH');
INSERT INTO CIRCUITO (NOMBRE, LONGITUD, CURVAS, CIUDAD, URBANO, CODPAIS) VALUES ('Autódromo Hermanos Rodríguez', 2090, 14, 'Ciudad de México', 'N', 'ME');
INSERT INTO CIRCUITO (NOMBRE, LONGITUD, CURVAS, CIUDAD, URBANO, CODPAIS) VALUES ('Circuito del aeropuerto Berlín-Tempelhof', 2375, 17, 'Berlin', 'SEMI', 'AL');
INSERT INTO CIRCUITO (NOMBRE, LONGITUD, CURVAS, CIUDAD, URBANO, CODPAIS) VALUES ('Circuito callejero de París', 1930, 14, 'Paris', 'S', 'FR');
INSERT INTO CIRCUITO (NOMBRE, LONGITUD, CURVAS, CIUDAD, URBANO, CODPAIS) VALUES ('Circuito callejero de Hong Kong', 1860, 10, 'Hong Kong', 'S', 'CH');

-- CARRERAS
CREATE TABLE CARRERA (
  FECHACARRERA DATE NOT NULL, 
  PERIODO VARCHAR2(7 CHAR) NOT NULL,
  NOMBRE_GP VARCHAR2(40 CHAR), 
  VUELTAS NUMBER,
  CIRCUITO VARCHAR2(50 CHAR),
  CONSTRAINT CARRERA_PK PRIMARY KEY (FECHACARRERA),
  CONSTRAINT CARRERA_TEMPORADA_FK FOREIGN KEY (PERIODO) REFERENCES TEMPORADA (PERIODO),
  CONSTRAINT CARRERA_CIRCUITO_FK FOREIGN KEY (CIRCUITO) REFERENCES CIRCUITO (NOMBRE)
);

INSERT INTO CARRERA (FECHACARRERA, PERIODO, NOMBRE_GP, VUELTAS, CIRCUITO) VALUES ('24/10/2016', '2016-17', 'Pekin ePrix', 26, 'Circuito del Parque Olímpico de Pekín');
INSERT INTO CARRERA (FECHACARRERA, PERIODO, NOMBRE_GP, VUELTAS, CIRCUITO) VALUES ('01/04/2017', '2016-17', 'Ciudad de México ePrix', 45, 'Autódromo Hermanos Rodríguez');
INSERT INTO CARRERA (FECHACARRERA, PERIODO, NOMBRE_GP, VUELTAS, CIRCUITO) VALUES ('03/12/2017', '2017-18', 'Hong Kong ePrix', 39, 'Circuito callejero de Hong Kong');
INSERT INTO CARRERA (FECHACARRERA, PERIODO, NOMBRE_GP, VUELTAS, CIRCUITO) VALUES ('19/05/2018', '2017-18', 'Berlín ePrix', 45, 'Circuito del aeropuerto Berlín-Tempelhof');
INSERT INTO CARRERA (FECHACARRERA, PERIODO, NOMBRE_GP, VUELTAS, CIRCUITO) VALUES ('28/04/2018', '2017-18', 'París ePrix', 49, 'Circuito callejero de París');


-- EQUIPOS
CREATE TABLE EQUIPO (
  NOMBRE VARCHAR2(40) NOT NULL, 
  CODPAIS CHAR(2), 
  ANO_FUNDACION INTEGER, 
  FUNDADOR VARCHAR2(100), 
  MOTOR VARCHAR2(50), 
  CONSTRAINT EQUIPO_PK PRIMARY KEY (NOMBRE),
  CONSTRAINT EQUIPO_PAIS_FK FOREIGN KEY (CODPAIS) REFERENCES PAIS (CODPAIS)
); 

INSERT INTO EQUIPO (NOMBRE, CODPAIS, ANO_FUNDACION, FUNDADOR, MOTOR) VALUES ('Audi Sport', 'AL', 2013, 'ABT Schaeffler', 'Audi');
INSERT INTO EQUIPO (NOMBRE, CODPAIS, ANO_FUNDACION, FUNDADOR, MOTOR) VALUES ('Renault', 'FR', 2014, 'Alain Prost', 'Nissan');
INSERT INTO EQUIPO (NOMBRE, CODPAIS, ANO_FUNDACION, FUNDADOR, MOTOR) VALUES ('Aguri', 'JA', 2014, 'Aguri Suzuki', 'McLaren-Renault');

-- PILOTOS
CREATE TABLE PILOTO (
  CODPILOTO VARCHAR2(7) NOT NULL, 
  NOMBRE VARCHAR2(100) NOT NULL, 
  CODPAIS CHAR(2) NOT NULL, 
  FECHANACIMIENTO DATE, 
  LUGARNACIMIENTO VARCHAR2(100), 
  SEXO CHAR(1) NOT NULL, 
  CONSTRAINT PILOTO_PK PRIMARY KEY (CODPILOTO),
  CONSTRAINT PILOTO_PAIS_FK FOREIGN KEY (CODPAIS) REFERENCES PAIS (CODPAIS),
  CONSTRAINT SEXO_CHK CHECK (SEXO IN ('H', 'M'))
);

INSERT INTO PILOTO (CODPILOTO, NOMBRE, CODPAIS, FECHANACIMIENTO, LUGARNACIMIENTO, SEXO) VALUES ('SEBABUE', 'Sébastien Buemi', 'SU', '31/10/1988', 'Aigle', 'H');
INSERT INTO PILOTO (CODPILOTO, NOMBRE, CODPAIS, FECHANACIMIENTO, LUGARNACIMIENTO, SEXO) VALUES ('NICOPRO', 'Nicolas Prost', 'FR', '18/08/1981', 'Loire', 'H');
INSERT INTO PILOTO (CODPILOTO, NOMBRE, CODPAIS, FECHANACIMIENTO, LUGARNACIMIENTO, SEXO) VALUES ('DANIABT', 'Daniel Abt', 'AL', '02/12/1992', 'Kempten', 'H');
INSERT INTO PILOTO (CODPILOTO, NOMBRE, CODPAIS, FECHANACIMIENTO, LUGARNACIMIENTO, SEXO) VALUES ('LUCAGRA', 'Lucas Di Grassi', 'BR', '11/08/1984', 'Sao Paulo', 'H');
INSERT INTO PILOTO (CODPILOTO, NOMBRE, CODPAIS, FECHANACIMIENTO, LUGARNACIMIENTO, SEXO) VALUES ('KATHLEG', 'Katherine Legge', 'UK', '12/07/1980', 'Guildford', 'M');

-- PILOTOSEQUIPO
CREATE TABLE PERTENECE (
  PERIODO VARCHAR2(7 CHAR) NOT NULL,
  CODPILOTO VARCHAR2(7) NOT NULL, 
  EQUIPO VARCHAR2(40) NOT NULL, 
  ROL CHAR(2) NOT NULL, 
  CONSTRAINT PERTENECE_PK PRIMARY KEY (PERIODO, CODPILOTO),
  CONSTRAINT PERTENECE_TEMPORADA_FK FOREIGN KEY (PERIODO) REFERENCES TEMPORADA (PERIODO),
  CONSTRAINT PERTENECE_PILOTO_FK FOREIGN KEY (CODPILOTO) REFERENCES PILOTO (CODPILOTO),
  CONSTRAINT PERTENECE_EQUIPO_FK FOREIGN KEY (EQUIPO) REFERENCES EQUIPO (NOMBRE),
  CONSTRAINT ROL_CHK CHECK (ROL IN ('PO', 'PR')) -- PO: Piloto oficial, PR: Piloto de pruebas.
);

INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2016-17', 'NICOPRO', 'Audi Sport', 'PO');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2017-18', 'NICOPRO', 'Renault', 'PO');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2016-17', 'LUCAGRA', 'Renault', 'PO');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2017-18', 'LUCAGRA', 'Audi Sport', 'PO');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2016-17', 'SEBABUE', 'Renault', 'PO');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2017-18', 'SEBABUE', 'Renault', 'PO');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2016-17', 'KATHLEG', 'Aguri', 'PO');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2017-18', 'KATHLEG', 'Aguri', 'PO');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2016-17', 'DANIABT', 'Audi Sport', 'PO');
INSERT INTO PERTENECE (PERIODO, CODPILOTO, EQUIPO, ROL) VALUES ('2017-18', 'DANIABT', 'Audi Sport', 'PO');

-- CARRERASPILOTOS
CREATE TABLE PARTICIPA (
  FECHACARRERA DATE NOT NULL,
  CODPILOTO VARCHAR2(7) NOT NULL, 
  POSICION_SALIDA NUMBER NOT NULL, 
  POSICION_LLEGADA NUMBER NOT NULL,
  TIEMPOVUELTARAPIDA NUMBER,
  CONSTRAINT PARTICIPA_PK PRIMARY KEY (FECHACARRERA, CODPILOTO),
  CONSTRAINT PARTICIPA_CARRERA_FK FOREIGN KEY (FECHACARRERA) REFERENCES CARRERA (FECHACARRERA),
  CONSTRAINT PARTICIPA_PILOTO_FK FOREIGN KEY (CODPILOTO) REFERENCES PILOTO (CODPILOTO),
  CONSTRAINT POSICION_SALIDA_CHK CHECK (POSICION_SALIDA > 0)
);

INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('24/10/2016','SEBABUE',1,1,1.12);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('24/10/2016','NICOPRO',2,5,1.33);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('24/10/2016','DANIABT',3,2,1.23);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('24/10/2016','LUCAGRA',4,3,1.37);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('24/10/2016','KATHLEG',5,4,1.44);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('01/04/2017','SEBABUE',5,4,1.19);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('01/04/2017','NICOPRO',4,2,1.25);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('01/04/2017','DANIABT',3,3,1.12);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('01/04/2017','LUCAGRA',2,1,1.26);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('01/04/2017','KATHLEG',1,5,1.19);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('03/12/2017','SEBABUE',4,5,1.12);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('03/12/2017','NICOPRO',5,3,1.23);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('03/12/2017','DANIABT',1,1,1.43);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('03/12/2017','LUCAGRA',2,2,1.32);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('03/12/2017','KATHLEG',3,4,1.21);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('19/05/2018','SEBABUE',2,2,2.11);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('19/05/2018','NICOPRO',3,3,1.12);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('19/05/2018','DANIABT',4,5,1.23);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('19/05/2018','LUCAGRA',5,1,1.18);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('19/05/2018','KATHLEG',1,4,1.22);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('28/04/2018','SEBABUE',3,1,1.43);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('28/04/2018','NICOPRO',4,3,1.12);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('28/04/2018','DANIABT',5,5,1.23);
INSERT INTO PARTICIPA (FECHACARRERA,CODPILOTO,POSICION_SALIDA,POSICION_LLEGADA,TIEMPOVUELTARAPIDA) VALUES ('28/04/2018','LUCAGRA',1,2,1.43);
commit;                                                                                                                                                                                                                                                                                                                                                                                                                                  