CREATE TABLE usuario(
cod		VARCHAR2(10),
nombre		VARCHAR2(15),
apellido	VARCHAR2(15) NOT NULL,
edad		NUMBER(2) ,
SEXO		VARCHAR2(1) DEFAULT 'M',
CONSTRAINT PK_usuario PRIMARY KEY (cod),
CONSTRAINT CH_EDAD CHECK(EDAD>14), 
CONSTRAINT CH_SEXO CHECK(SEXO IN ('V','M')) 
);

CREATE TABLE claselibro(
clase		VARCHAR2(1),
tiempo		NUMBER(5),
CONSTRAINT PK_claselibro PRIMARY KEY (clase)
);

CREATE TABLE libro(
isbn		VARCHAR2(10),
clase		VARCHAR2(1),
titulo		VARCHAR2(35) NOT NULL,
autor		VARCHAR2(15),
editorial	VARCHAR2(25),
CONSTRAINT PK_libro PRIMARY KEY (isbn),
CONSTRAINT Unica_libro UNIQUE (titulo),
CONSTRAINT FK_libro FOREIGN KEY (clase) REFERENCES claselibro (clase)
);

CREATE TABLE prestamo(
isbn		VARCHAR2(10),
cod		VARCHAR2(10),
fecha_ini	DATE NOT NULL,
fecha_fin	DATE,
CONSTRAINT PK_prestamo PRIMARY KEY (isbn,cod,fecha_ini),
CONSTRAINT FK1_prestamo FOREIGN KEY (isbn) REFERENCES libro (isbn),
CONSTRAINT FK2_prestamo FOREIGN KEY (cod) REFERENCES usuario(cod),
CONSTRAINT CH_FECHA CHECK(FECHA_FIN>FECHA_INI)
);