INSERT INTO usuario  (COD,NOMBRE,APELLIDO,EDAD) VALUES ('1','Alberto','VIZCAY',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('2','Pedro','AGOS',23);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('3','Luis','ALONSO',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('4','Juan','ARRONDO',65);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('5','María','AYAPE',13);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('6','Ana','AYERRA',23);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('7','Rakel','BRAVO',26);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('8','Juanan','BRENE',67);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('9','Jesús','CASTILLEJO',50);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('10','Itziar','CELAYA',54);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('11','Edurne','CIA',29);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('12','Cristina','CIORDIA',30);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('13','Leticia','CORRALES',32);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('14','Pedro María','DIAZ',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('15','Daniel','DOMINGUEZ',23);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('16','David','DOMINGUEZ',56);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('17','Alfonso','ECHARRI',34);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('18','Irene','ECHARRI',44);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('19','Izaskun','ECHEVERRÍA',45);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('20','Victoria','ESQUIROZ',40);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('21','Inmaculada','FLORES',21);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('22','Carmen','GALAR',20);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('23','Guadalupe','GARCES',24);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('24','Elvira','GARCIA',33);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('25','Gustavo','GARCIA',34);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('26','Christian','GARCIA',23);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('27','Naiara','GOÑI',33);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('28','Ainhoa','GUERRERO',90);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('29','Iñaki','HERNANDEZ',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('30','Harry','ILUNDAIN',24);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('31','Humberto','IRIGOYEN',45);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('32','Mikel','IRISARRI',10);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('33','Carmela','IRURRE',23);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('34','Begoña','JUSUE',26);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('35','Marisol','LAPIEZA',27);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('36','Mercedes','LAPUENTE',28);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('37','Nekane','LAS',26);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('38','Eugenia','LATASA',27);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('39','Escolástica','LIZARRAGA',28);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('40','Alfredo','LOPEZ',16);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('41','Sergio','LOPEZ',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('42','Pablo','LOPEZ',17);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('43','Santiago','LUQUI',55);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('44','Olga','MACAZAGA',67);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('45','Nuria','MARTINEZ',45);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('46','Cristina','MARTIRENA',55);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('47','Nerea','MARZO',77);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('48','Elisa','MIGUELEZ',88);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('49','Emilio','MONTANER',34);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('50','Javier','MUNIAIN',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('51','Eneko','NAPAL',43);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('52','Urko','OLAZARAN',26);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('53','Alex','OLIVA',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('54','José Carlos','OTANO',42);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('55','Andrés','PEREZ',25);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('56','Gabriel','PRIMICIA',25);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('57','Muskilda','PRZYLECKI',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('58','Paula','RAMIREZ',41);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('59','Mónica','RODRIGUEZ',25);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('60','Marta','RODRIGUEZ',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('61','Asun','ROMERO',25);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('62','Nicolás','ROSILLO',31);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('63','Andreu','TORRES',22);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('64','Oscar','UNZU',25);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('65','Joxan','UNZUE',31);
INSERT INTO usuario (COD,NOMBRE,APELLIDO,EDAD) VALUES ('66','Oier','URIZ',22);


INSERT INTO claselibro VALUES ('A',7);
INSERT INTO claselibro VALUES ('B',30);
INSERT INTO claselibro VALUES ('C',90);
INSERT INTO claselibro VALUES ('D',180);
INSERT INTO claselibro VALUES ('E',365);

INSERT INTO libro VALUES ('1A','A','Álgebra 1','Olaberría','mcgraw-hill');
INSERT INTO libro VALUES ('2B','B','Álgebra 2','Urtasun','mcgraw-hill');
INSERT INTO libro VALUES ('3A','C','Álgebra 3','Bujanda','mcgraw-hill');
INSERT INTO libro VALUES ('4B','D','Álgebra 4','Martirena','mcgraw-hill');
INSERT INTO libro VALUES ('5A','A','Álgebra 5','Esáin','mcgraw-hill');
INSERT INTO libro VALUES ('6C','B','Cálculo 1A','Urrutia','mcgraw-hill');
INSERT INTO libro VALUES ('7A','C','Cálculo 2B','Kricke','mcgraw-hill');
INSERT INTO libro VALUES ('8B','D','Cálculo 1C','Ulzurrun','mcgraw-hill');
INSERT INTO libro VALUES ('9A','A','Cálculo 2C','Jaukikoa','mcgraw-hill');
INSERT INTO libro VALUES ('10B','A','Cálculo diferencial','Maisterra','mcgraw-hill');
INSERT INTO libro VALUES ('11A','A','Programación en Pascal I','Urtasun','mcgraw-hill');
INSERT INTO libro VALUES ('12C','A','Programación II','Bujanda','mcgraw-hill');
INSERT INTO libro VALUES ('13A','A','Programación I','Olaberría','mcgraw-hill');
INSERT INTO libro VALUES ('14B','B','Windows 2000','Urtasun','mcgraw-hill');
INSERT INTO libro VALUES ('15A','C','Windows XP','Bujanda','Anaya');
INSERT INTO libro VALUES ('16B','D','Linux','Olaberría','Osborne');
INSERT INTO libro VALUES ('17A','A','VPN con IPSEC','Jaukikoa','Aranzadi');
INSERT INTO libro VALUES ('18C','B','Programación OO','Bujanda','Planeta');
INSERT INTO libro VALUES ('19B','C','Java','Olaberría','Oxford');
INSERT INTO libro VALUES ('20A','B','Inteligencia Artificial','Urtasun','Oxford');
INSERT INTO libro VALUES ('21C','B','Matemática discreta','Bujanda','Anaya');
INSERT INTO libro VALUES ('22B','B','Matemática aplicada','Ulzurrun','Anaya');
INSERT INTO libro VALUES ('19A','B','Matemática para niños','Urtasun','Anaya');
INSERT INTO libro VALUES ('20C','B','Fotografía digital','Bujanda','Anaya');
INSERT INTO libro VALUES ('21A','B','Java II','Olaberría','Anaya');
INSERT INTO libro VALUES ('22C','B','Servidores de aplicaciones','Urtasun','Anaya');
INSERT INTO libro VALUES ('23A','C','Oracle','Bujanda','Anaya');
INSERT INTO libro VALUES ('333C','D','PL-SQL','Olaberría','Anaya');
INSERT INTO libro VALUES ('25C','A','Administración de Oracle','Urtasun','Anaya');
INSERT INTO libro VALUES ('26C','B','Picasso','Urtasun','Anaya');
INSERT INTO libro VALUES ('222C','C','The Beatles','Olaberría','Anaya');
INSERT INTO libro VALUES ('28C','D','Yoga','Urtasun','Planeta');
INSERT INTO libro VALUES ('29C','A','Yoga I','Bujanda','Planeta');
INSERT INTO libro VALUES ('30C','B','Yoga II','Maisterra','Oxford');
INSERT INTO libro VALUES ('31C','C','Yoga III','Urtasun','mcgraw-hill');
INSERT INTO libro VALUES ('32C','C','Estadística I','Pérez','mcgraw-hill');
INSERT INTO libro VALUES ('313C','A','Estadística 2','Gómez','mcgraw-hill');
INSERT INTO libro VALUES ('34C','B','Mirar un cuadro','Gutierrez','mcgraw-hill');
INSERT INTO libro VALUES ('35C','C','Enología','Martínez','mcgraw-hill');
INSERT INTO libro VALUES ('36AC','D','La pesca de rio','Carro','mcgraw-hill');
INSERT INTO libro VALUES ('37C','A','La pesca de mar','Martínez','mcgraw-hill');
INSERT INTO libro VALUES ('38C','A','Macramé','Bujanda','mcgraw-hill');
INSERT INTO libro VALUES ('39C','C','Pintar un cuadro','Carro','Zeroa Multimedia');
INSERT INTO libro VALUES ('40R','D','Pintar dos cuadros','Urtasun','Zeroa Multimedia');
INSERT INTO libro VALUES ('82C','A','Drogas de diseño','Carro','Zeroa Multimedia');
INSERT INTO libro VALUES ('42C','B','Mecanografía I','Góngora','mcgraw-hill');
INSERT INTO libro VALUES ('43R','B','Mecanografía Avanzada','Urtasun','Planeta');
INSERT INTO libro VALUES ('88C','D','Mecanografía para informáticos','Pérez','Osborne');
INSERT INTO libro VALUES ('45C','A','Excel, ayuda a insertar','Roncal','Buenapista');


INSERT INTO prestamo VALUES ('1A','12','10/10/2018','12/10/2018');
INSERT INTO prestamo VALUES ('2B','13','11/10/2018','17/10/2018');
INSERT INTO prestamo VALUES ('45C','14','12/10/2018','14/10/2018');
INSERT INTO prestamo VALUES ('4B','15','13/10/2018','19/10/2018');
INSERT INTO prestamo VALUES ('5A','16','01/02/2017','03/02/2017');
INSERT INTO prestamo VALUES ('6C','17','10/03/2017','16/03/2017');
INSERT INTO prestamo VALUES ('7A','18','16/04/2017','31/05/2017');
INSERT INTO prestamo VALUES ('8B','19','23/05/2017','08/07/2017');
INSERT INTO prestamo VALUES ('9A','4','29/06/2017','13/08/2017');
INSERT INTO prestamo  (isbn,cod,fecha_ini) VALUES ('10B','5','05/08/2017');
INSERT INTO prestamo VALUES ('11A','6','11/09/2017','26/10/2017');
INSERT INTO prestamo VALUES ('12C','7','18/10/2017','03/12/2017');
INSERT INTO prestamo VALUES ('1A','8','26/03/2016','10/05/2016');
INSERT INTO prestamo VALUES ('45C','9','01/09/2014','17/10/2014');
INSERT INTO prestamo VALUES ('1A','10','08/02/2013','25/03/2013');
INSERT INTO prestamo VALUES ('45C','11','17/07/2011','28/07/2011');
INSERT INTO prestamo VALUES ('1A','19','23/09/2011','12/10/2011');
INSERT INTO prestamo VALUES ('1A','13','30/11/2011','13/12/2011');
INSERT INTO prestamo VALUES ('19B','1','06/02/2012','07/02/2012');
INSERT INTO prestamo  (isbn,cod,fecha_ini) VALUES ('20A','2','15/04/2012');
INSERT INTO prestamo VALUES ('21C','3','22/06/2012','25/06/2012');
INSERT INTO prestamo VALUES ('22B','4','29/08/2012','02/09/2012');
INSERT INTO prestamo VALUES ('19A','5','05/11/2012','10/11/2012');
INSERT INTO prestamo VALUES ('5A','1','06/09/2017','07/09/2017');
INSERT INTO prestamo  (isbn,cod,fecha_ini) VALUES ('6C','2','07/09/2017');
INSERT INTO prestamo VALUES ('7A','3','08/09/2017','11/09/2017');
INSERT INTO prestamo VALUES ('5A','4','09/09/2017','13/09/2017');
INSERT INTO prestamo VALUES ('6C','5','10/09/2017','15/09/2017');
INSERT INTO prestamo VALUES ('45C','10','11/09/2017','21/09/2017');
INSERT INTO prestamo VALUES ('45C','6','12/09/2017','18/09/2017');
INSERT INTO prestamo  (isbn,cod,fecha_ini) VALUES ('6C','6','04/07/2019');
INSERT INTO prestamo VALUES ('7A','6','05/07/2019','11/07/2019');
INSERT INTO prestamo VALUES ('29C','6','26/07/2019','01/08/2019');
INSERT INTO prestamo  (isbn,cod,fecha_ini) VALUES ('30C','6','07/07/2019');
INSERT INTO prestamo VALUES ('31C','34','08/07/2019','11/08/2019');
INSERT INTO prestamo VALUES ('32C','55','09/07/2019','02/09/2019');
INSERT INTO prestamo VALUES ('333C','19','30/11/2011','19/12/2011');
INSERT INTO prestamo VALUES ('34C','20','06/02/2012','26/02/2012');
INSERT INTO prestamo VALUES ('35C','21','15/04/2012','06/05/2012');
INSERT INTO prestamo VALUES ('36AC','22','22/06/2012','14/07/2012');
INSERT INTO prestamo VALUES ('37C','23','29/08/2012','21/09/2012');
INSERT INTO prestamo  (isbn,cod,fecha_ini) VALUES ('38C','24','05/11/2012');
INSERT INTO prestamo  (isbn,cod,fecha_ini) VALUES ('39C','25','07/09/2017');
INSERT INTO prestamo VALUES ('40R','4','08/09/2017','12/09/2017');
INSERT INTO prestamo  (isbn,cod,fecha_ini) VALUES ('82C','4','09/09/2017');
INSERT INTO prestamo VALUES ('333C','4','09/07/2019','13/07/2019');
INSERT INTO prestamo VALUES ('34C','4','10/07/2019','14/07/2019');
INSERT INTO prestamo  (isbn,cod,fecha_ini) VALUES ('88C','4','11/07/2019');
INSERT INTO prestamo VALUES ('45C','4','12/07/2019','16/07/2019');