/*1*/
SELECT E.DNI, E.SUELDO, E.NOMBRE, E.CUALIFICACION, H.NOMHOSP, H.CIUDAD
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE E.DNI<>10 AND E.DNI<>3 AND E.DNI<>5 AND E.SUELDO<=300 AND E.DNI=T.DNI AND T.CODHOSP=H.CODHOSP
ORDER BY H.NOMHOSP, E.CUALIFICACION, E.NOMBRE;
/*2*/
SELECT E.DNI, E.AP1, E.AP2, E.NOMBRE, (E.SUELDO*1.04) AS NUEVO_SUELDO
FROM EMPLEADO E, TRABAJA T
WHERE T.CODHOSP<>'H1' AND T.DNI=E.DNI AND(E.CUALIFICACION='ENFERMERO' OR E.CUALIFICACION='ENFERMERA')
ORDER BY NUEVO_SUELDO ASC;
/*3*/
SELECT DISTINCT H.NOMHOSP, H.CIUDAD
FROM HOSPITAL H, INGRESOS I
WHERE I.CODHOSP=H.CODHOSP AND I.FECHA>='01/01/2015' AND I.FECHA<='31/12/2015'
ORDER BY H.NOMHOSP ASC;
/*4*/
SELECT ('"'||E.NOMBRE||', '||E.AP1||' '||E.AP2||'"') AS NOMBREyAPELLIDOS, COUNT(T.CODHOSP) AS HOSPITALES
FROM TRABAJA T, EMPLEADO E
WHERE E.DNI=T.DNI 
GROUP BY ('"'||E.NOMBRE||', '||E.AP1||' '||E.AP2||'"')
HAVING COUNT(T.CODHOSP)>1
ORDER BY HOSPITALES DESC, NOMBREyAPELLIDOS ASC;
/*5*/
SELECT COUNT(T.DNI) AS TRABAJOS, MIN(E.SUELDO) AS SUELDO_MENOR, MAX(E.SUELDO) AS SUELDO_MAYOR, MIN(H.NUMEMP) AS EMPLEADOS_MENOR, MAX(H.NUMEMP) AS EMPLEADOS_MAYOR
FROM EMPLEADO E, TRABAJA T, HOSPITAL H
WHERE E.CUALIFICACION='AUXILIAR' AND E.DNI=T.DNI AND H.CODHOSP=T.CODHOSP;
/*6*/
SELECT D.NOMDEPT, D.CODDEPT, COUNT(I.HISTORIAL) AS INGRSOS, MIN(I.FECHA) AS PRIMER_INGRESO, MAX(I.FECHA) AS ULTIMO_INGRESO
FROM DEPHOSPITAL D, INGRESOS I, EMPLEADO E
WHERE D.CODDEPT=E.DEPAR AND E.DNI=I.DNI
GROUP BY D.NOMDEPT,D.CODDEPT
ORDER BY PRIMER_INGRESO ASC;