
prompt creando HOSPITAL;
CREATE TABLE HOSPITAL
(CODHOSP	VARCHAR2(4),
CIUDAD		VARCHAR2(15),
NOMHOSP		VARCHAR2(25) UNIQUE,
NUMEMP		NUMBER(3) DEFAULT 0,
CONSTRAINT CPHOSPITAL PRIMARY KEY (CODHOSP));


prompt creando DEPHOSPITAL;
CREATE TABLE DEPHOSPITAL
(CODDEPT		VARCHAR2(4),
NOMDEPT			VARCHAR2(25) UNIQUE,
CONSTRAINT CPDEPHOSPITAL PRIMARY KEY (CODDEPT));		

prompt creando EMPLEADO;
CREATE TABLE EMPLEADO
(DNI		VARCHAR2(3),
NOMBRE		VARCHAR2(15) NOT NULL,
AP1			VARCHAR2(25) NOT NULL,
AP2			VARCHAR2(25) NOT NULL,
DIRECCION	VARCHAR2(40),
CUALIFICACION	VARCHAR2(15) NOT NULL,
SUELDO		NUMBER(5,2) DEFAULT 0,
DEPAR		VARCHAR2(15),
CONSTRAINT CPDEMPLEADO PRIMARY KEY (DNI),
CONSTRAINT CFEMPLEADO FOREIGN KEY (DEPAR) 
	REFERENCES DEPHOSPITAL (CODDEPT) ON DELETE CASCADE,
CONSTRAINT CHECKEMPLEADO CHECK 
(CUALIFICACION IN ('DOCTOR','DOCTORA', 'ENFERMERO', 'ENFERMERA', 'AUXILIAR')));
		


prompt creando TRABAJA;
CREATE TABLE TRABAJA
(CODHOSP	VARCHAR2(4),
DNI		VARCHAR2(3),
CONSTRAINT CPTRABAJA PRIMARY KEY (CODHOSP,DNI),
CONSTRAINT CFTRABAJA1 FOREIGN KEY (CODHOSP) 
	REFERENCES HOSPITAL (CODHOSP) ON DELETE CASCADE,
CONSTRAINT CFTRABAJA2 FOREIGN KEY (DNI) 
	REFERENCES EMPLEADO (DNI) ON DELETE CASCADE);


prompt creando PACIENTE;
CREATE TABLE PACIENTE
(DNI		VARCHAR2(3) UNIQUE,
NOMBRE		VARCHAR2(25) NOT NULL,
HISTORIAL	VARCHAR2(3),
CONSTRAINT CPPACIENTE PRIMARY KEY (HISTORIAL));


prompt creando INGRESOS;
CREATE TABLE INGRESOS
(HISTORIAL	VARCHAR2(3),
DNI		VARCHAR2(3),
CODHOSP		VARCHAR2(4),
FECHA		DATE DEFAULT SYSDATE,
CONSTRAINT CPINGRESOS PRIMARY KEY (HISTORIAL,CODHOSP,DNI,FECHA),
CONSTRAINT CFINGRESOS1 FOREIGN KEY (HISTORIAL) REFERENCES PACIENTE (HISTORIAL) ON DELETE CASCADE,
CONSTRAINT CFINGRESOS2 FOREIGN KEY (DNI) REFERENCES EMPLEADO (DNI) ON DELETE CASCADE,
CONSTRAINT CFINGRESOS3 FOREIGN KEY (CODHOSP) REFERENCES HOSPITAL (CODHOSP) ON DELETE CASCADE);


