/* Ejercicio 1*/
SELECT COUNT (*)
FROM ASIGNATURAS
;

/* Ejercicio 2*/
SELECT COUNT (*)
FROM ASIGNATURAS
WHERE ANUALIDAD='A'
;

/* Ejercicio 3*/
SELECT MAX (A.ALUMNOS) 
FROM ASIGNATURAS A
;
/*SELECT *
FROM ASIGNATURAS A
WHERE A.ALUMNOS IN (
        SELECT MAX (A.ALUMNOS) 
        FROM ASIGNATURAS A)
;*/

/* Ejercicio 4*/
SELECT AVG(ALUMNOS) AS MEDIAALUMNOS
FROM ASIGNATURAS
;

/* Ejercicio 5*/
SELECT SUM (ALUMNOS)
FROM ASIGNATURAS
;

/* Ejercicio 6*/
SELECT PROFESOR, COUNT (*) DOCENCIA
FROM DOCENCIA
GROUP BY PROFESOR
ORDER BY PROFESOR
;

/* Ejercicio 7*/
SELECT PROFESOR, COUNT (*) DOCENCIA
FROM DOCENCIA
GROUP BY PROFESOR
HAVING COUNT (*) > 10
ORDER BY PROFESOR
;

/* Ejercicio 8*/
SELECT  SUM( A.HORAS_TEORIA) AS TOTALTEORIA, SUM(A.HORAS_PRACTICA) AS TOTALPRACTICAS
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS
;

/* Ejercicio 9*/
SELECT  SUM( A.HORAS_TEORIA) AS TOTALTEORIA, SUM (A.HORAS_PRACTICA) AS TOTALPRACTICAS
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS AND A.ANUALIDAD='A' AND D.PROFESOR>30
;

/* Ejercicio 10*/
SELECT COUNT(A.SIGLAS) AS NºASIGNATURAS, AVG(A.HORAS_PRACTICA) AS MEDIAPRACTICA
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS AND A.ANUALIDAD='A' AND D.PROFESOR>30
;

/* Ejercicio 11*/
SELECT MAX(L.CAPACIDAD) AS CAPACIDADMAXIMA
FROM LOCALES L
;

/* Ejercicio 12*/
SELECT MAX(L.CAPACIDAD) AS MAXCAPACIDAD
FROM LOCALES L, DOCENCIA D, ASIGNATURAS A
WHERE L.CODIGO=D.LOCAL AND D.SIGLAS=A.SIGLAS AND A.HORAS_PRACTICA>0
;

/* Ejercicio 13*/
SELECT COUNT(L.SITUACION) AS LOCALES_PLANTA_PRIMERA
FROM LOCALES L
WHERE L.SITUACION LIKE 'Planta Primera%'
;

/* Ejercicio 14*/
SELECT L.SITUACION AS SITUACION, COUNT(L.SITUACION) AS NºSITUACION
FROM LOCALES L
GROUP BY L.SITUACION
ORDER BY L.SITUACION
;

/* Ejercicio 15*/
SELECT D.DIA, MIN(D.HORA) AS PRIMERA_HORA, MAX(D.HORA) AS ULTIMA_HORA
FROM DOCENCIA D
GROUP BY D.DIA
ORDER BY D.DIA
;

/* Ejercicio 16*/
SELECT A.ANUALIDAD, COUNT(A.SIGLAS) AS NºASIGNATURAS, AVG(A.CREDITOS) AS MEDIA_CREDITOS, MIN(A.ALUMNOS) AS MINIMOSALUMNOS
FROM ASIGNATURAS A
WHERE A.ANUALIDAD NOT LIKE 'A' OR A.ANUALIDAD IS NULL
GROUP BY A.ANUALIDAD
ORDER BY A.ANUALIDAD
;

/* Ejercicio 17*/
SELECT A.SIGLAS, A.NOMBRE
FROM ASIGNATURAS A, DOCENCIA D
WHERE (A.SIGLAS = D.SIGLAS)
GROUP BY A.SIGLAS, A.NOMBRE
HAVING COUNT (D.ID) BETWEEN 10 AND 20
ORDER BY A.NOMBRE
;

/* Ejercicio 18*/
SELECT D.HORA, COUNT(D.DIA) AS NºDIAS
FROM DOCENCIA D, ASIGNATURAS A
WHERE D.SIGLAS=A.SIGLAS AND A.NOMBRE = 'Algebra' 
GROUP BY D.HORA
HAVING COUNT(D.DIA)>1
ORDER BY NºDIAS DESC, D.HORA ASC
;

/* Ejercicio 19*/
SELECT A.CURSO, MAX(A.ALUMNOS) AS MAYOR_NUM_ALUMNOS, MIN(A.ALUMNOS) AS MENOR_NUM_ALUMNOS, AVG(A.ALUMNOS) AS MEDIA_NUM_ALUMNOS
FROM ASIGNATURAS A, DOCENCIA D
WHERE D.SIGLAS=A.SIGLAS
GROUP BY A.CURSO
;

/* Ejercicio 20*/
SELECT L.NOMBRE, L.EDIFICIO, MAX(D.CURSO)
FROM LOCALES L, DOCENCIA D
WHERE D.LOCAL=L.CODIGO
GROUP BY L.NOMBRE, L.EDIFICIO 
ORDER BY L.NOMBRE
;

/* Ejercicio 21*/
SELECT A.NOMBRE, D.DIA, COUNT(DISTINCT P.CODIGO) AS NUM_PROFESORES
FROM ASIGNATURAS A, DOCENCIA D, PROFESORES P
WHERE A.SIGLAS=D.SIGLAS AND D.PROFESOR=P.CODIGO AND P.DEDICACION NOT LIKE '%TC%' 
GROUP BY A.NOMBRE, D.DIA
HAVING COUNT (DISTINCT P.CODIGO) > 1
;

/* Ejercicio 22*/
SELECT A.CURSO, '('||A.SIGLAS||')' , A.NOMBRE, SUM(A.GRUPOS_PRACTICA), SUM(A.GRUPOS_TEORIA)
FROM ASIGNATURAS A
WHERE A.CREDITOS>9 AND A.GRUPOS_PRACTICA>0 AND A.GRUPOS_TEORIA>0
GROUP BY A.CURSO, '('||A.SIGLAS||')', A.NOMBRE
ORDER BY A.CURSO, A.NOMBRE
;

/* Ejercicio 23*/
SELECT A.NOMBRE, '(' ||A.SIGLAS|| ')', AVG(A.ALUMNOS)/COUNT(D.SIGLAS)
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS
GROUP BY A.NOMBRE, '('||A.SIGLAS||')'
;

/* Ejercicio 24*/
SELECT G.NOMBRE, COUNT (DISTINCT D.PROFESOR) AS DISTINTOS_PROFES
FROM DOCENCIA D, GRUPOS G
WHERE (D.CURSO=G.CURSO) AND (D.CLASE=G.CLASE) AND (D.GRUPO=G.CODIGO)
GROUP BY G.NOMBRE
;

/* Ejercicio 25*/
SELECT G.NOMBRE
FROM GRUPOS G, DOCENCIA D
WHERE (D.CURSO=G.CURSO) AND (D.CLASE=G.CLASE) AND (D.GRUPO=G.CODIGO)
GROUP BY G.NOMBRE
HAVING COUNT (DISTINCT D.PROFESOR)=1
;

/* Ejercicio 26*/
SELECT COUNT(A.NOMBRE) AS CUENTA_ASIGNATURAS, P.APELLIDO1||' '||P.APELLIDO2||', '||P.NOMBRE_PILA AS "NOMBRE Y APELLIDOS"
FROM ASIGNATURAS A, DOCENCIA D, PROFESORES P
WHERE A.SIGLAS=D.SIGLAS AND D.PROFESOR=P.CODIGO
GROUP BY P.APELLIDO1, P.APELLIDO2 ,P.NOMBRE_PILA
ORDER BY P.APELLIDO1, P.APELLIDO2 ,P.NOMBRE_PILA
;

/* Ejercicio 27*/
SELECT  P.APELLIDO1||' '||P.APELLIDO2||', '||P.NOMBRE_PILA AS "NOMBRE Y APELLIDOS"
FROM PROFESOR P, DOCENCIA D, ASIGNATURAS A
WHERE P.CODIGO=D.PROFESOR AND D.SIGLAS=A.SIGLAS  
GROUP BY P.APELLIDO1, P.APELLIDO2 ,P.NOMBRE_PILA
HAVING COUNT (DISTINCT D.SIGLAS) > 1
ORDER BY P.APELLIDO1, P.APELLIDO2 ,P.NOMBRE_PILA
;

/* Ejercicio 28*/
SELECT L.NOMBRE, L.EDIFICIO, L.CAPACIDAD-AVG(A.ALUMNOS) AS DIFFCAPACIDAD-ALUMNOS, A.NOMBRE, COUNT(A.CLASE) AS CLASE
FROM LOCALES L, DOCENCIA D, ASIGNATURAS A
WHERE A.SUGLAS=D.SIGLAS AND D.LOCAL=L.CODIGO AND (A.HORAS_PRACTICA > 0)
GROUP BY L.NOMBRE, L.EDIFICIO, A.NOMBRE, L.CAPACIDAD, A.ALUMNOS
HAVING L.CAPACIDAD/AVG(A.ALUMNOS)<1
;
/*VER SI EL 28 ESTA BIEN*/































