CREATE TABLE CLIENTE(
    COD_CLIENTE NUMBER(10),
    NOMBRE VARCHAR(10) NOT NULL,
    DIRECCION VARCHAR2(30) NOT NULL,
    TFNO NUMBER(9) NOT NULL, 
    TIPO VARCHAR(1) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_USER),
    CONSTRAINT CH_TIPO CHECK (TIPO IN('E', 'B', 'N') )
);


CREATE TABLE ORDEN(
    COD_VENTA NUMBER(10),
    FECHA_PETICION DATE NOT NULL,
    FECHA_ENVIO DATE NOT NULL, 
    FORMA_PAGO VARCHAR(1) NOT NULL,
    CONSTRAINT PK_ORDEN PRIMARY KEY (COD_VENTA),
    CONSTRAINT CH_FECHA CHECK (FECHA_PETICION < FECHA_ENVIO),
    CONSTRAINT CH_PAGO CHECK (FORMA_PAGO IN ('A', 'C', 'G') )
);


CREATE TABLE RAL(
    COD_RAL NUMBER(5),
    GRADO_ROJO NUMBER(3),
    GRADO_VERDE NUMBER(3),
    GRADE_AZUL NUMBER(3),
    CONSTRAINT PK_RAL PRIMARY KEY (COD_RAL)
);


CREATE TABLE ARTICULO(
    COD_ARTICULO VARCHAR (20),
    DESCRIPCION VARCHAR(50) NOT NULL,
    NUM_STOCK NUMBER(5) NOT NULL,
    MAQUINA_F VARCHAR(10) NOT NULL,
    CONSTRAINT PK_ARTICULO PRIMARY KEY (COD_ARTICULO),
    CONSTRAINT FK_MAQUINA FOREIGN KEY (COD_MAQUINA)
);


CREATE TABLE MAQUINA(
    COD_MAQUINA NUMBER (10),
    DESCRIPCION VARCHAR2(50),
    SITUACION VARCHAR(30),
    CONSTRAINT PK_MAQUINA PRIMARY KEY (COD_MAQUINA)
    CONSTRAINT FK_PROD FOREIGN KEY (COD_PROD) 
);


CREATE TABLE PRODUCCION(
    COD_PROD NUMBER(10),
    NUM_ART_OK NUMBER(5) NOT NULL,
    NUM_ART_NOK NUMBER(5) NOT NULL,
    TIEMPO_EXEC NUMBER(3);
    CONSTRAINT PK_PROD PRIMARY KEY (COD_PROD),
    CONSTRAINT CH_OK CHECK (NUM_ART_OK > -1), 
    CONSTRAINT CH_NOK CHECK (NUM_ART_NOK > -1),


























