/* Practica 3 */

/* Ejercicio 1 */
SELECT 

/* Ejercicio 3 */
SELECT H.CODHOSP, H.NOMHOSP, H.NUMEMP
FROM HOSPITAL H
WHERE (H.CIUDAD LIKE '%Pamplona%')
GROUP BY H.CODHOSP, H.NOMHOSP, H.NUMEMP

/* Ejercicio 4 */
SELECT COUNT(DISTINCT H.CODHOSP)
FROM HOSPITAL H

/* Ejercicio 5 */
SELECT COUNT(DISTINCT H.CODHOSP)
FROM HOSPITAL H
WHERE (H.NUMEMP > 4)

/* Ejercicio 13 */
SELECT COUNT(*)
FROM INGRESOS I
WHERE (I.FECHA > '01/01/2018')

/* Ejercicio 14 */
SELECT COUNT(*) INGRESOS
FROM INGRESOS I, EMPLEADO E, DEPHOSPITAL D
WHERE (I.FECHA > '01/01/2018') AND (I.DNI = E.DNI) AND (E.DEPAR = D.CODDEPT) AND (D.NOMDEPT LIKE '%PEDIATRIA%')

/* Ejercicio 15 */


