/* Practica 3 */


/* Ejercicio 3 */
SELECT H.CODHOSP, H.NOMHOSP, H.NUMEMP
FROM HOSPITAL H
WHERE (H.CIUDAD LIKE '%Pamplona%')
GROUP BY H.CODHOSP, H.NOMHOSP, H.NUMEMP;

/* Ejercicio 4 */
SELECT COUNT(DISTINCT H.CODHOSP)
FROM HOSPITAL H;

/* Ejercicio 5 */
SELECT COUNT(DISTINCT H.CODHOSP)
FROM HOSPITAL H
WHERE (H.NUMEMP > 4);

/* Ejercicio 13 */
SELECT COUNT(*)
FROM INGRESOS I
WHERE (I.FECHA > '01/01/2018');

/* Ejercicio 14 */
SELECT COUNT(*) INGRESOS
FROM INGRESOS I, EMPLEADO E, DEPHOSPITAL D
WHERE (I.FECHA > '01/01/2018') AND (I.DNI = E.DNI) AND (E.DEPAR = D.CODDEPT) AND (D.NOMDEPT LIKE '%PEDIATRIA%');

/* Ejercicio 15: Cuando hay tantos campos al agrupar, se obtiene el mismo resultado que con GROUP BY */
SELECT I.HISTORIAL, I.DNI, I.CODHOSP, I.FECHA, E.AP1, H.NOMHOSP
FROM INGRESOS I, EMPLEADO E, HOSPITAL H, PACIENTE P
WHERE (P.HISTORIAL = I.HISTORIAL) AND (I.DNI = E.DNI) AND (I.CODHOSP = H.CODHOSP);
--GROUP BY I.HISTORIAL, I.DNI, I.CODHOSP, I.FECHA, E.AP1, H.NOMHOSP

/* Ejercicio 16 */
SELECT SUM(H.NUMEMP) TOTAL_EMPLEADOS
FROM HOSPITAL H;



/* Ejercicio 17 */
SELECT H.CODHOSP, H.NUMEMP TOTAL_EMPLEADOS
FROM HOSPITAL H
WHERE (H.NUMEMP > 0)
GROUP BY H.CODHOSP, H.NUMEMP;

/* Ejercicio 18 */
SELECT MAX(E.SUELDO), MIN(E.SUELDO), ROUND(AVG(E.SUELDO), 4)
FROM EMPLEADO E;

/* Ejercicio 19 */
SELECT MAX(E.SUELDO), MIN(E.SUELDO), ROUND(AVG(E.SUELDO), 4)
FROM EMPLEADO E, INGRESOS I, PACIENTE P
WHERE (P.NOMBRE LIKE '%García%') AND (P.HISTORIAL = I.HISTORIAL) AND (I.DNI = E.DNI);

/* Ejercicio 20 */
SELECT MAX(E.SUELDO), MIN(E.SUELDO), ROUND(AVG(E.SUELDO), 4)
FROM EMPLEADO E, DEPHOSPITAL D
WHERE (D.CODDEPT LIKE '%D3%') AND (D.CODDEPT = E.DEPAR);

/* Ejercicio 21 */
SELECT D.CODDEPT, ROUND(AVG(E.SUELDO), 4)
FROM DEPHOSPITAL D, EMPLEADO E
WHERE (D.CODDEPT = E.DEPAR)
GROUP BY D.CODDEPT;

/* Ejercicio 22 */
SELECT D.CODDEPT, ROUND(AVG(E.SUELDO), 4)
FROM DEPHOSPITAL D, EMPLEADO E
WHERE (D.CODDEPT = E.DEPAR)
HAVING  AVG(E.SUELDO) > 400
GROUP BY D.CODDEPT; 

/* Ejercicio 23 */
SELECT E.CUALIFICACION, SUM(E.SUELDO)
FROM EMPLEADO E
GROUP BY E.CUALIFICACION
ORDER BY SUM(E.SUELDO) DESC;

/* Ejercicio 24 */
SELECT H.NOMHOSP, H.NUMEMP
FROM HOSPITAL H
WHERE H.NUME > 0;















