/* Practica 1 */

/*Ejercicio 1*/
SELECT CODIGO, NOMBRE
FROM DEPARTAMENTOS

/* Ejercicio 2 */
SELECT A.DEPARTAMENTO, A.CODIGO, A.NOMBRE
FROM AREAS A

/* Ejercicio 3 */
SELECT *
FROM LOCALES L
WHERE (L.CAPACIDAD > 30)

/* Ejercicio 4 */
SELECT *
FROM LOCALES L
WHERE ((L.CAPACIDAD > 30) AND (L.EDIFICIO = 'EGB'))

/* Ejercicio 5 */
SELECT *
FROM DOCENCIA D
ORDER BY D.PROFESOR, D.SIGLAS
/* duda: orden */

/* Ejercicio 6 */
SELECT D.ID, D.PROFESOR, D.SIGLAS, D.PERIODICIDAD
FROM DOCENCIA D
ORDER BY D.ID

/* Ejercicio 6 BIS*/
SELECT D.ID,D.PROFESOR,D.SIGLAS,A.ANUALIDAD,A.CREDITOS
FROM ASIGNATURAS A,DOCENCIA D
WHERE D.SIGLAS=A.SIGLAS;

/* Ejericicio 7 */
SELECT *
FROM ASIGNATURAS A
WHERE (A.HORAS_TEORIA > 0) AND (A.HORAS_PRACTICA > 0)

/* Ejericicio 7 BIS */
SELECT *
FROM ASIGNATURAS 
WHERE (HORAS_TEORIA > 0) AND (HORAS_PRACTICA > 0)


/* Ejericicio 8 */
SELECT *
FROM ASIGNATURAS A
WHERE (A.HORAS_TEORIA > 0) OR (A.HORAS_PRACTICA > 0)

/* Ejericicio 9 */
SELECT *
FROM ASIGNATURAS A
WHERE ((A.HORAS_TEORIA > 0) OR (A.HORAS_PRACTICA > 0)) AND (A.ALUMNOS > 30)

/* Ejericicio 10 */
SELECT DISTINCT D.GRUPO
FROM DOCENCIA D
ORDER BY D.GRUPO ASC

/* Ejericicio 11 */
SELECT A.SIGLAS, A.ALUMNOS
FROM ASIGNATURAS A
WHERE A.ANUALIDAD = 'A'

/* Ejercicio 12 */
SELECT L.EDIFICIO 
FROM LOCALES L
WHERE (L.EDIFICIO LIKE 'E%')

/* Ejercicio 13 */
SELECT *
FROM LOCALES L
WHERE (L.CAPACIDAD BETWEEN 30 AND 80)

/* Ejercicio 14 */
SELECT *
FROM LOCALES L
WHERE (L.SITUACION NOT LIKE 'Planta Primera%' )

/* Ejercicio 15 */
SELECT SIGLAS, NOMBRE, CREDITOS, CURSO, ANUALIDAD, CLASE, HORAS_TEORIA, HORAS_PRACTICA *1.1 "Previsión Profesorado"
FROM ASIGNATURAS 
WHERE (HORAS_PRACTICA > 0)

/* Ejercicio 16 */
SELECT 'El area de codigo '||A.CODIGO||' pertence al departamento '||A.DEPARTAMENTO
FROM AREAS A

/* Ejercicio 17 */
SELECT DISTINCT P.CODIGO||'-'||P.APELLIDO1||'    '||P.APELLIDO2||'   , '|| P.NOMBRE_PILA 
FROM PROFESORES P
WHERE P.ACTIVO = 1

/* Extra */
SELECT *
FROM ASIGNATURAS
WHERE ANUALIDAD IS NULL





